In [1]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel
import numpy as np
from difflib import SequenceMatcher
import re

In [2]:
# --- Configuration ---
COMBINED_THRESHOLD = 0.80
COLUMN_TO_STANDARDIZE = 'dimension'

In [2]:
# --- Preprocessing Function ---
def preprocess(text):
    """Converts text to lowercase, replaces underscores, and cleans special characters."""
    if isinstance(text, str):
        text = text.lower()
        # Replace underscores with spaces for better n-gram/ratio results
        text = text.replace('_', ' ')
        text = re.sub(r'[^a-z0-9\s]', '', text)
        return text.strip()
    return ''

In [4]:
# Function to calculate fuzzy ratio using difflib
def difflib_ratio(a, b):
    return SequenceMatcher(None, a, b).ratio()

In [30]:
# 1. Load Data
df = pd.read_csv("role_count_aggregation/athlete.csv")
dimension_counts = df[COLUMN_TO_STANDARDIZE].value_counts()
unique_dimensions = dimension_counts.index.tolist()
unique_processed = [preprocess(d) for d in unique_dimensions]

In [31]:
#check if any df with unknow exists
# Show only rows where label is 'unknown' or 'None'
df[df['label'].isin(['unknown', 'None'])]

           cohort                    dimension    label  count
4      atmosphere          aesthetic_qualities  unknown      2
36     atmosphere                         mood  unknown      3
102        camera                 focal_length  unknown      6
109        camera                      framing  unknown      2
113        camera                  perspective  unknown      4
116   environment                  aisle_width  unknown     10
157   environment               indoor_outdoor  unknown     50
208   environment             time_of_day_hint  unknown     10
269   environment                      weather  unknown      8
347       objects                         side  unknown      1
768        people              eyewear_present  unknown      2
772        people          facial_hair_present  unknown      3
784        people               gaze_direction  unknown     14
791        people                 hair_present  unknown     53
797        people                   hair_style  unknown      2
881         texts                   font_style  unknown     12
905        totals                       images  unknown     10
906        totals             object_instances  unknown    181
907        totals             people_instances  unknown     10
908        totals               text_instances  unknown      8
1002  uncertainty  total_uncertainty_instances  unknown     70

In [7]:
# 2. Calculate Cosine Similarity (TF-IDF on Char N-Grams)
vectorizer = TfidfVectorizer(min_df=1, analyzer='char', ngram_range=(2, 4))
tfidf_matrix = vectorizer.fit_transform(unique_processed)
cosine_sim = linear_kernel(tfidf_matrix, tfidf_matrix)

In [8]:
# 3. Calculate Fuzzy Ratio (difflib-based)
N = len(unique_processed)
fuzzy_sim = np.zeros((N, N))
for i in range(N):
    for j in range(i, N):
        ratio = difflib_ratio(unique_processed[i], unique_processed[j])
        fuzzy_sim[i, j] = ratio
        fuzzy_sim[j, i] = ratio

In [9]:
# 4. Combine Similarities
combined_sim = (cosine_sim + fuzzy_sim) / 2

In [23]:
# 5. Create Standardization Map (Clustering)
standard_map = {}
sorted_unique_dims = dimension_counts.sort_values(ascending=False).index.tolist()

unique_to_processed = {original: preprocess(original) for original in unique_dimensions}
processed_to_index = {processed: i for i, processed in enumerate(unique_processed)}

for original_standard_str in sorted_unique_dims:
    if original_standard_str in standard_map: continue

    processed_standard_str = unique_to_processed.get(original_standard_str)
    if not processed_standard_str: continue

    idx_list = [i for i, proc_str in enumerate(unique_processed) if proc_str == processed_standard_str]
    if not idx_list: continue
    idx = idx_list[0]

    similar_indices = np.where(combined_sim[idx] >= COMBINED_THRESHOLD)[0]

    for sim_idx in similar_indices:
        variant_str = unique_dimensions[sim_idx]
        if variant_str not in standard_map:
            standard_map[variant_str] = original_standard_str

In [24]:
# 6. Apply the mapping and create new columns
df['standardized_dimension'] = df[COLUMN_TO_STANDARDIZE].apply(lambda x: standard_map.get(x, x))

df['original_dimension_if_changed'] = df.apply(
    lambda row: row[COLUMN_TO_STANDARDIZE] if row[COLUMN_TO_STANDARDIZE] != row['standardized_dimension'] else 'not changed',
    axis=1
)
# Assuming your standardized data is loaded into df
df_aggregated = df.groupby(['cohort', 'standardized_dimension', 'label'], as_index=False)['count'].sum()

In [25]:
df

,cohort,dimension,label,count,standardized_dimension,original_dimension_if_changed
0,atmosphere,aesthetic_qualities,cinematic,14,aesthetic_qualities,not changed
1,atmosphere,aesthetic_qualities,dreamy,3,aesthetic_qualities,not changed
2,atmosphere,aesthetic_qualities,gritty,1,aesthetic_qualities,not changed
3,atmosphere,aesthetic_qualities,realistic,12,aesthetic_qualities,not changed
4,atmosphere,aesthetic_qualities,unknown,2,aesthetic_qualities,not changed
...,...,...,...,...,...,...
1092,uncertainty,uncertainty,time_of_day_hint_left_unknown_despite_daylight...,1,uncertainty,not changed
1093,uncertainty,uncertainty,two_bright_green_round_fruits_type_uncertain,1,uncertainty,not changed
1094,uncertainty,uncertainty,upper_cabinet_interior_contents_partially_occl...,1,uncertainty,not changed
1095,uncertainty,uncertainty,weather_not_visible,1,uncertainty,not changed
1096,uncertainty,uncertainty,windowsill_baskets_partially_occluded,1,uncertainty,not changed

In [26]:
# Filter to show only rows where the dimension was changed
df[df['original_dimension_if_changed'] != 'not changed']

,cohort,dimension,label,count,standardized_dimension,original_dimension_if_changed
5,atmosphere,aesthetic_quality,cinematic,5,aesthetic_qualities,aesthetic_quality
6,atmosphere,aesthetic_quality,gritty,1,aesthetic_qualities,aesthetic_quality
7,atmosphere,aesthetic_quality,realistic,4,aesthetic_qualities,aesthetic_quality
17,atmosphere,dominant_palette_mapped,black,2,dominant_palette,dominant_palette_mapped
18,atmosphere,dominant_palette_mapped,blue,2,dominant_palette,dominant_palette_mapped
19,atmosphere,dominant_palette_mapped,brown,5,dominant_palette,dominant_palette_mapped
20,atmosphere,dominant_palette_mapped,cyan,2,dominant_palette,dominant_palette_mapped
21,atmosphere,lighting_color_temperature,cool,8,color_temperature,lighting_color_temperature
22,atmosphere,lighting_color_temperature,neutral,4,color_temperature,lighting_color_temperature
23,atmosphere,lighting_color_temperature,warm,14,color_temperature,lighting_color_temperature
49,background,object_counts_by_position_total,background_center,9,object_counts_by_position,object_counts_by_position_total
50,background,object_counts_by_position_total,background_left,4,object_counts_by_position,object_counts_by_position_total
51,background,object_counts_by_position_total,background_right,5,object_counts_by_position,object_counts_by_position_total
52,background,object_counts_by_position_total,foreground_center,14,object_counts_by_position,object_counts_by_position_total
53,background,object_counts_by_position_total,foreground_left,4,object_counts_by_position,object_counts_by_position_total
54,background,object_counts_by_position_total,foreground_right,2,object_counts_by_position,object_counts_by_position_total
55,background,object_counts_by_position_total,midground_center,6,object_counts_by_position,object_counts_by_position_total
56,background,object_counts_by_position_total,midground_left,3,object_counts_by_position,object_counts_by_position_total
57,background,object_counts_by_position_total,midground_right,1,object_counts_by_position,object_counts_by_position_total
830,people,pose_gaze_direction,down,4,gaze_direction,pose_gaze_direction
831,people,pose_gaze_direction,left,1,gaze_direction,pose_gaze_direction
832,people,pose_gaze_direction,right,2,gaze_direction,pose_gaze_direction
833,people,pose_gaze_direction,up,2,gaze_direction,pose_gaze_direction

# Batch Preprocessing of All CSV Files

Now we'll apply the preprocessing to both `dimension` and `label` columns across all CSV files in the role_count_aggregation directory.

In [5]:
import os
import glob
from pathlib import Path

def preprocess_dataframe_columns(df, columns_to_process=['dimension', 'label'], threshold=0.80):
    """
    Apply standardization preprocessing to specified columns in a dataframe.
    
    Args:
        df: pandas DataFrame
        columns_to_process: list of column names to standardize
        threshold: similarity threshold for clustering similar values
    
    Returns:
        processed_df: DataFrame with standardized columns and tracking columns
    """
    processed_df = df.copy()
    
    for column in columns_to_process:
        if column not in df.columns:
            print(f"Warning: Column '{column}' not found in dataframe. Skipping.")
            continue
            
        print(f"Processing column: {column}")
        
        # Get unique values and their counts
        value_counts = processed_df[column].value_counts()
        unique_values = value_counts.index.tolist()
        unique_processed = [preprocess(str(val)) for val in unique_values]
        
        # Skip if no unique values
        if len(unique_values) == 0:
            continue
            
        # Calculate similarities if more than one unique value
        if len(unique_values) > 1:
            # Calculate Cosine Similarity (TF-IDF on Char N-Grams)
            vectorizer = TfidfVectorizer(min_df=1, analyzer='char', ngram_range=(2, 4))
            tfidf_matrix = vectorizer.fit_transform(unique_processed)
            cosine_sim = linear_kernel(tfidf_matrix, tfidf_matrix)
            
            # Calculate Fuzzy Ratio
            N = len(unique_processed)
            fuzzy_sim = np.zeros((N, N))
            for i in range(N):
                for j in range(i, N):
                    ratio = difflib_ratio(unique_processed[i], unique_processed[j])
                    fuzzy_sim[i, j] = ratio
                    fuzzy_sim[j, i] = ratio
            
            # Combine similarities
            combined_sim = (cosine_sim + fuzzy_sim) / 2
        else:
            # If only one unique value, create identity matrix
            combined_sim = np.array([[1.0]])
        
        # Create standardization map
        standard_map = {}
        sorted_unique_values = value_counts.sort_values(ascending=False).index.tolist()
        
        value_to_processed = {original: preprocess(str(original)) for original in unique_values}
        processed_to_index = {processed: i for i, processed in enumerate(unique_processed)}
        
        for original_standard_val in sorted_unique_values:
            if original_standard_val in standard_map:
                continue
                
            processed_standard_val = value_to_processed.get(original_standard_val)
            if not processed_standard_val:
                continue
                
            idx_list = [i for i, proc_val in enumerate(unique_processed) if proc_val == processed_standard_val]
            if not idx_list:
                continue
            idx = idx_list[0]
            
            similar_indices = np.where(combined_sim[idx] >= threshold)[0]
            
            for sim_idx in similar_indices:
                variant_val = unique_values[sim_idx]
                if variant_val not in standard_map:
                    standard_map[variant_val] = original_standard_val
        
        # Apply standardization
        standardized_col_name = f'standardized_{column}'
        original_col_name = f'original_{column}_if_changed'
        
        processed_df[standardized_col_name] = processed_df[column].apply(lambda x: standard_map.get(x, x))
        processed_df[original_col_name] = processed_df.apply(
            lambda row: row[column] if row[column] != row[standardized_col_name] else 'not changed',
            axis=1
        )
        
        changes_count = (processed_df[original_col_name] != 'not changed').sum()
        print(f"  - Standardized {changes_count} values in column '{column}'")
    
    return processed_df

In [6]:
def process_all_csv_files(input_dir, output_dir, columns_to_process=['dimension', 'label'], threshold=0.80):
    """
    Process all CSV files in input directory and save cleaned versions to output directory.
    
    Args:
        input_dir: path to directory containing CSV files
        output_dir: path to directory where cleaned files will be saved
        columns_to_process: list of columns to standardize
        threshold: similarity threshold for clustering
    """
    # Create output directory if it doesn't exist
    os.makedirs(output_dir, exist_ok=True)
    
    # Get all CSV files
    csv_files = glob.glob(os.path.join(input_dir, "*.csv"))
    
    if not csv_files:
        print(f"No CSV files found in {input_dir}")
        return
    
    print(f"Found {len(csv_files)} CSV files to process")
    print("=" * 60)
    
    processing_summary = []
    
    for csv_file in csv_files:
        filename = os.path.basename(csv_file)
        print(f"\nProcessing: {filename}")
        
        try:
            # Load the CSV file
            df = pd.read_csv(csv_file)
            print(f"  - Loaded {len(df)} rows, {len(df.columns)} columns")
            
            # Apply preprocessing
            processed_df = preprocess_dataframe_columns(df, columns_to_process, threshold)
            
            # Create aggregated version (group by standardized columns)
            groupby_cols = ['cohort'] + [f'standardized_{col}' for col in columns_to_process if col in df.columns]
            if all(col in processed_df.columns for col in groupby_cols):
                aggregated_df = processed_df.groupby(groupby_cols, as_index=False)['count'].sum()
                print(f"  - Aggregated to {len(aggregated_df)} rows")
            else:
                aggregated_df = processed_df
                print(f"  - No aggregation applied (missing required columns)")
            
            # Save processed file
            output_file = os.path.join(output_dir, filename)
            aggregated_df.to_csv(output_file, index=False)
            print(f"  - Saved to: {output_file}")
            
            # Track processing summary
            changes_summary = {}
            for col in columns_to_process:
                if col in df.columns:
                    original_col = f'original_{col}_if_changed'
                    if original_col in processed_df.columns:
                        changes_count = (processed_df[original_col] != 'not changed').sum()
                        changes_summary[col] = changes_count
            
            processing_summary.append({
                'file': filename,
                'original_rows': len(df),
                'processed_rows': len(aggregated_df),
                'changes': changes_summary
            })
            
        except Exception as e:
            print(f"  - ERROR processing {filename}: {str(e)}")
            processing_summary.append({
                'file': filename,
                'error': str(e)
            })
    
    # Print summary
    print("\n" + "=" * 60)
    print("PROCESSING SUMMARY")
    print("=" * 60)
    
    for summary in processing_summary:
        print(f"\nFile: {summary['file']}")
        if 'error' in summary:
            print(f"  ❌ Error: {summary['error']}")
        else:
            print(f"  📊 Rows: {summary['original_rows']} → {summary['processed_rows']}")
            if summary['changes']:
                for col, changes in summary['changes'].items():
                    print(f"  🔄 {col}: {changes} standardizations")
    
    print(f"\n✅ Processing complete! All files saved to: {output_dir}")
    return processing_summary

In [7]:
# Set up paths
INPUT_DIR = "files/role_count_aggregation"
OUTPUT_DIR = "cleanData"
COLUMNS_TO_PROCESS = ['dimension', 'label']
THRESHOLD = 0.80

# Process all CSV files
summary = process_all_csv_files(
    input_dir=INPUT_DIR,
    output_dir=OUTPUT_DIR,
    columns_to_process=COLUMNS_TO_PROCESS,
    threshold=THRESHOLD
)

Found 10 CSV files to process
============================================================

Processing: farmer.csv
  - Loaded 935 rows, 4 columns
Processing column: dimension
  - Standardized 22 values in column 'dimension'
Processing column: label
  - Standardized 38 values in column 'label'
  - Aggregated to 890 rows
  - Saved to: cleanData/farmer.csv

Processing: ceo.csv
  - Loaded 977 rows, 4 columns
Processing column: dimension
  - Standardized 16 values in column 'dimension'
Processing column: label
  - Standardized 54 values in column 'label'
  - Aggregated to 915 rows
  - Saved to: cleanData/ceo.csv

Processing: dancer.csv
  - Loaded 928 rows, 4 columns
Processing column: dimension
  - Standardized 60 values in column 'dimension'
Processing column: label
  - Standardized 24 values in column 'label'
  - Aggregated to 892 rows
  - Saved to: cleanData/dancer.csv

Processing: housekeeper.csv
  - Loaded 1141 rows, 4 columns
Processing column: dimension
  - Standardized 15 values in column 'dimension'
Processing column: label
  - Standardized 31 values in column 'label'
  - Aggregated to 1106 rows
  - Saved to: cleanData/housekeeper.csv

Processing: police_officer.csv
  - Loaded 1183 rows, 4 columns
Processing column: dimension
  - Standardized 51 values in column 'dimension'
Processing column: label
  - Standardized 55 values in column 'label'
  - Aggregated to 1098 rows
  - Saved to: cleanData/police_officer.csv

Processing: chef.csv
  - Loaded 852 rows, 4 columns
Processing column: dimension
  - Standardized 12 values in column 'dimension'
Processing column: label
  - Standardized 39 values in column 'label'
  - Aggregated to 810 rows
  - Saved to: cleanData/chef.csv

Processing: athlete.csv
  - Loaded 1097 rows, 4 columns
Processing column: dimension
  - Standardized 23 values in column 'dimension'
Processing column: label
  - Standardized 41 values in column 'label'
  - Aggregated to 1046 rows
  - Saved to: cleanData/athlete.csv

Processing: bus_driver.csv
  - Loaded 1455 rows, 4 columns
Processing column: dimension
  - Standardized 41 values in column 'dimension'
Processing column: label
  - Standardized 67 values in column 'label'
  - Aggregated to 1364 rows
  - Saved to: cleanData/bus_driver.csv

Processing: janitor.csv
  - Loaded 1157 rows, 4 columns
Processing column: dimension
  - Standardized 43 values in column 'dimension'
Processing column: label
  - Standardized 50 values in column 'label'
  - Aggregated to 1091 rows
  - Saved to: cleanData/janitor.csv

Processing: musician.csv
  - Loaded 818 rows, 4 columns
Processing column: dimension
  - Standardized 20 values in column 'dimension'
Processing column: label
  - Standardized 29 values in column 'label'
  - Aggregated to 782 rows
  - Saved to: cleanData/musician.csv

============================================================
PROCESSING SUMMARY
============================================================

File: farmer.csv
  📊 Rows: 935 → 890
  🔄 dimension: 22 standardizations
  🔄 label: 38 standardizations

File: ceo.csv
  📊 Rows: 977 → 915
  🔄 dimension: 16 standardizations
  🔄 label: 54 standardizations

File: dancer.csv
  📊 Rows: 928 → 892
  🔄 dimension: 60 standardizations
  🔄 label: 24 standardizations

File: housekeeper.csv
  📊 Rows: 1141 → 1106
  🔄 dimension: 15 standardizations
  🔄 label: 31 standardizations

File: police_officer.csv
  📊 Rows: 1183 → 1098
  🔄 dimension: 51 standardizations
  🔄 label: 55 standardizations

File: chef.csv
  📊 Rows: 852 → 810
  🔄 dimension: 12 standardizations
  🔄 label: 39 standardizations

File: athlete.csv
  📊 Rows: 1097 → 1046
  🔄 dimension: 23 standardizations
  🔄 label: 41 standardizations

File: bus_driver.csv
  📊 Rows: 1455 → 1364
  🔄 dimension: 41 standardizations
  🔄 label: 67 standardizations

File: janitor.csv
  📊 Rows: 1157 → 1091
  🔄 dimension: 43 standardizations
  🔄 label: 50 standardizations

File: musician.csv
  📊 Rows: 818 → 782
  🔄 dimension: 20 standardizations
  🔄 label: 29 standardizations

✅ Processing complete! All files saved to: cleanData

In [8]:
# Verify results - show sample of cleaned data
print("Verification: Sample of cleaned data")
print("=" * 40)

# Check if cleanData directory was created
if os.path.exists(OUTPUT_DIR):
    cleaned_files = glob.glob(os.path.join(OUTPUT_DIR, "*.csv"))
    print(f"✅ Created {len(cleaned_files)} cleaned files in '{OUTPUT_DIR}/' directory")
    
    # Show sample from first file
    if cleaned_files:
        sample_file = cleaned_files[0]
        sample_df = pd.read_csv(sample_file)
        
        print(f"\nSample from {os.path.basename(sample_file)}:")
        print(f"Columns: {list(sample_df.columns)}")
        print(f"Shape: {sample_df.shape}")
        print("\nFirst 5 rows:")
        print(sample_df.head())
        
        # Show any standardizations that occurred
        for col in COLUMNS_TO_PROCESS:
            standardized_col = f'standardized_{col}'
            original_col = f'original_{col}_if_changed'
            
            if standardized_col in sample_df.columns and original_col in sample_df.columns:
                changes = sample_df[sample_df[original_col] != 'not changed']
                if len(changes) > 0:
                    print(f"\n{col.upper()} standardizations in this file:")
                    print(changes[[col, standardized_col, original_col]].head())
else:
    print("❌ cleanData directory was not created")

Verification: Sample of cleaned data
========================================
✅ Created 10 cleaned files in 'cleanData/' directory

Sample from farmer.csv:
Columns: ['cohort', 'standardized_dimension', 'standardized_label', 'count']
Shape: (890, 4)

First 5 rows:
       cohort standardized_dimension standardized_label  count
0  atmosphere    aesthetic_qualities          cinematic     21
1  atmosphere    aesthetic_qualities             dreamy      2
2  atmosphere    aesthetic_qualities          realistic     17
3  atmosphere    aesthetic_qualities            unknown      5
4  atmosphere      color_temperature               cool      1

# Remove Unknown Values and Update Files

Now we'll remove all rows containing 'unknown' values from both dimension and label columns, then update the cleaned files.

In [9]:
def remove_unknown_values_from_files(input_dir, columns_to_check=['standardized_dimension', 'standardized_label']):
    """
    Remove all rows containing 'unknown' values from specified columns and update files.
    
    Args:
        input_dir: directory containing the cleaned CSV files
        columns_to_check: list of columns to check for 'unknown' values
    
    Returns:
        summary of removed rows per file
    """
    csv_files = glob.glob(os.path.join(input_dir, "*.csv"))
    
    if not csv_files:
        print(f"No CSV files found in {input_dir}")
        return []
    
    print(f"Removing 'unknown' values from {len(csv_files)} files...")
    print("=" * 60)
    
    removal_summary = []
    
    for csv_file in csv_files:
        filename = os.path.basename(csv_file)
        print(f"\nProcessing: {filename}")
        
        try:
            # Load the file
            df = pd.read_csv(csv_file)
            original_rows = len(df)
            print(f"  - Original rows: {original_rows}")
            
            # Check for unknown values in each column
            unknown_counts = {}
            total_unknown_rows = 0
            
            # Create a mask for rows to keep (not containing 'unknown')
            keep_mask = pd.Series([True] * len(df))
            
            for col in columns_to_check:
                if col in df.columns:
                    # Find rows with 'unknown' values (case insensitive)
                    unknown_mask = df[col].astype(str).str.lower() == 'unknown'
                    unknown_count = unknown_mask.sum()
                    unknown_counts[col] = unknown_count
                    
                    if unknown_count > 0:
                        print(f"  - Found {unknown_count} 'unknown' values in column '{col}'")
                        # Update keep_mask to exclude rows with unknown values
                        keep_mask = keep_mask & ~unknown_mask
                else:
                    print(f"  - Column '{col}' not found in file")
            
            # Apply the filter
            df_filtered = df[keep_mask].copy()
            final_rows = len(df_filtered)
            rows_removed = original_rows - final_rows
            
            print(f"  - Rows removed: {rows_removed}")
            print(f"  - Final rows: {final_rows}")
            
            # Save the updated file (overwrite the original)
            df_filtered.to_csv(csv_file, index=False)
            print(f"  - Updated file saved: {csv_file}")
            
            removal_summary.append({
                'file': filename,
                'original_rows': original_rows,
                'final_rows': final_rows,
                'rows_removed': rows_removed,
                'unknown_counts': unknown_counts
            })
            
        except Exception as e:
            print(f"  - ERROR processing {filename}: {str(e)}")
            removal_summary.append({
                'file': filename,
                'error': str(e)
            })
    
    # Print summary
    print("\n" + "=" * 60)
    print("UNKNOWN VALUE REMOVAL SUMMARY")
    print("=" * 60)
    
    total_removed = 0
    for summary in removal_summary:
        print(f"\nFile: {summary['file']}")
        if 'error' in summary:
            print(f"  ❌ Error: {summary['error']}")
        else:
            print(f"  📊 Rows: {summary['original_rows']} → {summary['final_rows']} (removed: {summary['rows_removed']})")
            total_removed += summary['rows_removed']
            
            if summary['unknown_counts']:
                for col, count in summary['unknown_counts'].items():
                    if count > 0:
                        print(f"  🗑️ {col}: {count} unknown values removed")
    
    print(f"\n✅ Total rows removed across all files: {total_removed}")
    return removal_summary

In [10]:
# Execute the unknown value removal
removal_summary = remove_unknown_values_from_files(
    input_dir=OUTPUT_DIR,
    columns_to_check=['standardized_dimension', 'standardized_label']
)

Removing 'unknown' values from 10 files...
============================================================

Processing: farmer.csv
  - Original rows: 890
  - Found 50 'unknown' values in column 'standardized_label'
  - Rows removed: 50
  - Final rows: 840
  - Updated file saved: cleanData/farmer.csv

Processing: ceo.csv
  - Original rows: 915
  - Found 48 'unknown' values in column 'standardized_label'
  - Rows removed: 48
  - Final rows: 867
  - Updated file saved: cleanData/ceo.csv

Processing: dancer.csv
  - Original rows: 892
  - Found 46 'unknown' values in column 'standardized_label'
  - Rows removed: 46
  - Final rows: 846
  - Updated file saved: cleanData/dancer.csv

Processing: housekeeper.csv
  - Original rows: 1106
  - Found 41 'unknown' values in column 'standardized_label'
  - Rows removed: 41
  - Final rows: 1065
  - Updated file saved: cleanData/housekeeper.csv

Processing: police_officer.csv
  - Original rows: 1098
  - Found 48 'unknown' values in column 'standardized_label'
  - Rows removed: 48
  - Final rows: 1050
  - Updated file saved: cleanData/police_officer.csv

Processing: chef.csv
  - Original rows: 810
  - Found 46 'unknown' values in column 'standardized_label'
  - Rows removed: 46
  - Final rows: 764
  - Updated file saved: cleanData/chef.csv

Processing: athlete.csv
  - Original rows: 1046
  - Found 21 'unknown' values in column 'standardized_label'
  - Rows removed: 21
  - Final rows: 1025
  - Updated file saved: cleanData/athlete.csv

Processing: bus_driver.csv
  - Original rows: 1364
  - Found 40 'unknown' values in column 'standardized_label'
  - Rows removed: 40
  - Final rows: 1324
  - Updated file saved: cleanData/bus_driver.csv

Processing: janitor.csv
  - Original rows: 1091
  - Found 42 'unknown' values in column 'standardized_label'
  - Rows removed: 42
  - Final rows: 1049
  - Updated file saved: cleanData/janitor.csv

Processing: musician.csv
  - Original rows: 782
  - Found 5 'unknown' values in column 'standardized_label'
  - Rows removed: 5
  - Final rows: 777
  - Updated file saved: cleanData/musician.csv

============================================================
UNKNOWN VALUE REMOVAL SUMMARY
============================================================

File: farmer.csv
  📊 Rows: 890 → 840 (removed: 50)
  🗑️ standardized_label: 50 unknown values removed

File: ceo.csv
  📊 Rows: 915 → 867 (removed: 48)
  🗑️ standardized_label: 48 unknown values removed

File: dancer.csv
  📊 Rows: 892 → 846 (removed: 46)
  🗑️ standardized_label: 46 unknown values removed

File: housekeeper.csv
  📊 Rows: 1106 → 1065 (removed: 41)
  🗑️ standardized_label: 41 unknown values removed

File: police_officer.csv
  📊 Rows: 1098 → 1050 (removed: 48)
  🗑️ standardized_label: 48 unknown values removed

File: chef.csv
  📊 Rows: 810 → 764 (removed: 46)
  🗑️ standardized_label: 46 unknown values removed

File: athlete.csv
  📊 Rows: 1046 → 1025 (removed: 21)
  🗑️ standardized_label: 21 unknown values removed

File: bus_driver.csv
  📊 Rows: 1364 → 1324 (removed: 40)
  🗑️ standardized_label: 40 unknown values removed

File: janitor.csv
  📊 Rows: 1091 → 1049 (removed: 42)
  🗑️ standardized_label: 42 unknown values removed

File: musician.csv
  📊 Rows: 782 → 777 (removed: 5)
  🗑️ standardized_label: 5 unknown values removed

✅ Total rows removed across all files: 387

In [11]:
# Verify that unknown values have been removed
print("Verification: Checking for remaining 'unknown' values")
print("=" * 50)

cleaned_files = glob.glob(os.path.join(OUTPUT_DIR, "*.csv"))
total_unknown_found = 0

for csv_file in cleaned_files:
    filename = os.path.basename(csv_file)
    df = pd.read_csv(csv_file)
    
    # Check each standardized column for unknown values
    unknown_in_file = 0
    for col in ['standardized_dimension', 'standardized_label']:
        if col in df.columns:
            unknown_count = (df[col].astype(str).str.lower() == 'unknown').sum()
            if unknown_count > 0:
                print(f"⚠️  {filename}: {unknown_count} 'unknown' values found in {col}")
                unknown_in_file += unknown_count
    
    total_unknown_found += unknown_in_file

if total_unknown_found == 0:
    print("✅ Success! No 'unknown' values found in any file.")
    
    # Show sample of updated data
    sample_file = cleaned_files[0]
    sample_df = pd.read_csv(sample_file)
    print(f"\nSample from updated {os.path.basename(sample_file)}:")
    print(f"Shape: {sample_df.shape}")
    print("\nFirst 5 rows:")
    print(sample_df.head())
    
    # Show unique values in standardized columns to confirm no 'unknown'
    for col in ['standardized_dimension', 'standardized_label']:
        if col in sample_df.columns:
            unique_vals = sample_df[col].unique()
            print(f"\nUnique values in {col} (first 10): {unique_vals[:10]}")
            if 'unknown' in unique_vals or 'Unknown' in unique_vals:
                print(f"⚠️  Still contains 'unknown' values!")
            else:
                print(f"✅ No 'unknown' values in {col}")
else:
    print(f"❌ Still found {total_unknown_found} 'unknown' values across all files")

Verification: Checking for remaining 'unknown' values
==================================================
✅ Success! No 'unknown' values found in any file.

Sample from updated farmer.csv:
Shape: (840, 4)

First 5 rows:
       cohort standardized_dimension standardized_label  count
0  atmosphere    aesthetic_qualities          cinematic     21
1  atmosphere    aesthetic_qualities             dreamy      2
2  atmosphere    aesthetic_qualities          realistic     17
3  atmosphere      color_temperature               cool      1
4  atmosphere      color_temperature            neutral      1

Unique values in standardized_dimension (first 10): ['aesthetic_qualities' 'color_temperature' 'dominant_palette'
 'lighting_profile_aesthetic_qualities'
 'lighting_profile_color_temperature' 'lighting_profile_contrast_level'
 'lighting_saturation_level' 'mood' 'palette' 'palette_color']
✅ No 'unknown' values in standardized_dimension

Unique values in standardized_label (first 10): ['cinematic' 'dreamy' 'realistic' 'cool' 'neutral' 'warm' 'brown'
 'quality' 'high' 'medium']
✅ No 'unknown' values in standardized_label

In [12]:
# Final Summary of Complete Preprocessing Pipeline
print("🎯 COMPLETE PREPROCESSING PIPELINE SUMMARY")
print("=" * 60)

# Count total rows in final cleaned files
total_final_rows = 0
cleaned_files = glob.glob(os.path.join(OUTPUT_DIR, "*.csv"))

print(f"📁 Processed files: {len(cleaned_files)}")

for csv_file in cleaned_files:
    df = pd.read_csv(csv_file)
    rows = len(df)
    total_final_rows += rows
    filename = os.path.basename(csv_file)
    print(f"   - {filename}: {rows} rows")

print(f"\n📊 Total final rows across all files: {total_final_rows}")

print(f"\n✅ COMPLETED OPERATIONS:")
print(f"   1. ✅ Standardized 'dimension' and 'label' columns using similarity matching (threshold: {THRESHOLD})")
print(f"   2. ✅ Aggregated duplicate rows after standardization")
print(f"   3. ✅ Removed all rows containing 'unknown' values")
print(f"   4. ✅ Updated and saved all files in '{OUTPUT_DIR}/' directory")

print(f"\n🧹 DATA QUALITY:")
print(f"   - No 'unknown' values remain in any file")
print(f"   - All similar values have been standardized to consistent forms")
print(f"   - Duplicate entries have been aggregated with summed counts")

print(f"\n🎉 All CSV files are now cleaned and ready for analysis!")

🎯 COMPLETE PREPROCESSING PIPELINE SUMMARY
============================================================
📁 Processed files: 10
   - farmer.csv: 840 rows
   - ceo.csv: 867 rows
   - dancer.csv: 846 rows
   - housekeeper.csv: 1065 rows
   - police_officer.csv: 1050 rows
   - chef.csv: 764 rows
   - athlete.csv: 1025 rows
   - bus_driver.csv: 1324 rows
   - janitor.csv: 1049 rows
   - musician.csv: 777 rows

📊 Total final rows across all files: 9607

✅ COMPLETED OPERATIONS:
   1. ✅ Standardized 'dimension' and 'label' columns using similarity matching (threshold: 0.8)
   2. ✅ Aggregated duplicate rows after standardization
   3. ✅ Removed all rows containing 'unknown' values
   4. ✅ Updated and saved all files in 'cleanData/' directory

🧹 DATA QUALITY:
   - No 'unknown' values remain in any file
   - All similar values have been standardized to consistent forms
   - Duplicate entries have been aggregated with summed counts

🎉 All CSV files are now cleaned and ready for analysis!

# Process All Folders and Create Clean Data Structure

Now we'll process all folders under the `files` directory and create a cleanData folder with subfolders that have "clean" added to their original names.

In [13]:
def process_all_folders_with_clean_structure(base_files_dir="files", base_output_dir="cleanData", 
                                           columns_to_process=['dimension', 'label'], threshold=0.80):
    """
    Process all folders under base_files_dir and create cleanData structure with 'clean' suffix.
    
    Args:
        base_files_dir: directory containing all the folders to process
        base_output_dir: base directory for clean data (will create subfolders here)
        columns_to_process: list of columns to standardize
        threshold: similarity threshold for clustering
    """
    
    # Get all subdirectories in the files folder
    files_path = Path(base_files_dir)
    if not files_path.exists():
        print(f"❌ Base files directory not found: {base_files_dir}")
        return
    
    # Find all subdirectories (ignore files like .DS_Store and CSV files)
    subdirs = [d for d in files_path.iterdir() if d.is_dir()]
    
    if not subdirs:
        print(f"No subdirectories found in {base_files_dir}")
        return
    
    print(f"Found {len(subdirs)} folders to process:")
    for subdir in subdirs:
        print(f"  - {subdir.name}")
    
    print("\n" + "=" * 80)
    
    # Create base output directory
    os.makedirs(base_output_dir, exist_ok=True)
    
    all_summaries = {}
    
    for subdir in subdirs:
        folder_name = subdir.name
        clean_folder_name = f"{folder_name}_clean"
        
        print(f"\n🔄 Processing folder: {folder_name}")
        print(f"📁 Output folder: {clean_folder_name}")
        
        # Create output directory for this folder
        output_folder_path = os.path.join(base_output_dir, clean_folder_name)
        os.makedirs(output_folder_path, exist_ok=True)
        
        # Process all CSV files in this subfolder
        input_folder_path = str(subdir)
        summary = process_all_csv_files(
            input_dir=input_folder_path,
            output_dir=output_folder_path,
            columns_to_process=columns_to_process,
            threshold=threshold
        )
        
        # Remove unknown values from the processed files
        print(f"\n🧹 Removing unknown values from {clean_folder_name}...")
        removal_summary = remove_unknown_values_from_files(
            input_dir=output_folder_path,
            columns_to_check=[f'standardized_{col}' for col in columns_to_process]
        )
        
        all_summaries[folder_name] = {
            'processing_summary': summary,
            'removal_summary': removal_summary,
            'output_path': output_folder_path
        }
        
        print(f"✅ Completed processing {folder_name} → {clean_folder_name}")
    
    return all_summaries

In [14]:
# Execute processing of all folders
print("🚀 Starting batch processing of all folders...")
print("=" * 80)

# Process all folders and create clean structure
all_folder_summaries = process_all_folders_with_clean_structure(
    base_files_dir="files",
    base_output_dir="cleanData",
    columns_to_process=['dimension', 'label'],
    threshold=0.80
)

🚀 Starting batch processing of all folders...
================================================================================
Found 4 folders to process:
  - Context-aware_Related_CA-R
  - Context-aware_Unrelated_CA-U
  - role_count_aggregation
  - Context-free_CF

================================================================================

🔄 Processing folder: Context-aware_Related_CA-R
📁 Output folder: Context-aware_Related_CA-R_clean
Found 9 CSV files to process
============================================================

Processing: Context-aware_Related_CA-R_housekeeper.csv
  - Loaded 436 rows, 4 columns
Processing column: dimension
  - Standardized 1 values in column 'dimension'
Processing column: label
  - Standardized 8 values in column 'label'
  - Aggregated to 429 rows
  - Saved to: cleanData/Context-aware_Related_CA-R_clean/Context-aware_Related_CA-R_housekeeper.csv

Processing: Context-aware_Related_CA-R_chef.csv
  - Loaded 407 rows, 4 columns
Processing column: dimension
  - Standardized 0 values in column 'dimension'
Processing column: label
  - Standardized 6 values in column 'label'
  - Aggregated to 402 rows
  - Saved to: cleanData/Context-aware_Related_CA-R_clean/Context-aware_Related_CA-R_chef.csv

Processing: Context-aware_Related_CA-R_farmer.csv
  - Loaded 470 rows, 4 columns
Processing column: dimension
  - Standardized 9 values in column 'dimension'
Processing column: label
  - Standardized 5 values in column 'label'
  - Aggregated to 458 rows
  - Saved to: cleanData/Context-aware_Related_CA-R_clean/Context-aware_Related_CA-R_farmer.csv

Processing: Context-aware_Related_CA-R_dancer.csv
  - Loaded 427 rows, 4 columns
Processing column: dimension
  - Standardized 0 values in column 'dimension'
Processing column: label
  - Standardized 7 values in column 'label'
  - Aggregated to 421 rows
  - Saved to: cleanData/Context-aware_Related_CA-R_clean/Context-aware_Related_CA-R_dancer.csv

Processing: Context-aware_Related_CA-R_bus_driver.csv
  - Loaded 757 rows, 4 columns
Processing column: dimension
  - Standardized 18 values in column 'dimension'
Processing column: label
  - Standardized 23 values in column 'label'
  - Aggregated to 728 rows
  - Saved to: cleanData/Context-aware_Related_CA-R_clean/Context-aware_Related_CA-R_bus_driver.csv

Processing: Context-aware_Related_CA-R_janitor.csv
  - Loaded 506 rows, 4 columns
Processing column: dimension
  - Standardized 15 values in column 'dimension'
Processing column: label
  - Standardized 11 values in column 'label'
  - Aggregated to 488 rows
  - Saved to: cleanData/Context-aware_Related_CA-R_clean/Context-aware_Related_CA-R_janitor.csv

Processing: Context-aware_Related_CA-R_athlete.csv
  - Loaded 423 rows, 4 columns
Processing column: dimension
  - Standardized 16 values in column 'dimension'
Processing column: label
  - Standardized 8 values in column 'label'
  - Aggregated to 402 rows
  - Saved to: cleanData/Context-aware_Related_CA-R_clean/Context-aware_Related_CA-R_athlete.csv

Processing: Context-aware_Related_CA-R_ceo.csv
  - Loaded 507 rows, 4 columns
Processing column: dimension
  - Standardized 0 values in column 'dimension'
Processing column: label
  - Standardized 8 values in column 'label'
  - Aggregated to 500 rows
  - Saved to: cleanData/Context-aware_Related_CA-R_clean/Context-aware_Related_CA-R_ceo.csv

Processing: Context-aware_Related_CA-R_police_officer.csv
  - Loaded 716 rows, 4 columns
Processing column: dimension
  - Standardized 23 values in column 'dimension'
Processing column: label
  - Standardized 13 values in column 'label'
  - Aggregated to 694 rows
  - Saved to: cleanData/Context-aware_Related_CA-R_clean/Context-aware_Related_CA-R_police_officer.csv

============================================================
PROCESSING SUMMARY
============================================================

File: Context-aware_Related_CA-R_housekeeper.csv
  📊 Rows: 436 → 429
  🔄 dimension: 1 standardizations
  🔄 label: 8 standardizations

File: Context-aware_Related_CA-R_chef.csv
  📊 Rows: 407 → 402
  🔄 dimension: 0 standardizations
  🔄 label: 6 standardizations

File: Context-aware_Related_CA-R_farmer.csv
  📊 Rows: 470 → 458
  🔄 dimension: 9 standardizations
  🔄 label: 5 standardizations

File: Context-aware_Related_CA-R_dancer.csv
  📊 Rows: 427 → 421
  🔄 dimension: 0 standardizations
  🔄 label: 7 standardizations

File: Context-aware_Related_CA-R_bus_driver.csv
  📊 Rows: 757 → 728
  🔄 dimension: 18 standardizations
  🔄 label: 23 standardizations

File: Context-aware_Related_CA-R_janitor.csv
  📊 Rows: 506 → 488
  🔄 dimension: 15 standardizations
  🔄 label: 11 standardizations

File: Context-aware_Related_CA-R_athlete.csv
  📊 Rows: 423 → 402
  🔄 dimension: 16 standardizations
  🔄 label: 8 standardizations

File: Context-aware_Related_CA-R_ceo.csv
  📊 Rows: 507 → 500
  🔄 dimension: 0 standardizations
  🔄 label: 8 standardizations

File: Context-aware_Related_CA-R_police_officer.csv
  📊 Rows: 716 → 694
  🔄 dimension: 23 standardizations
  🔄 label: 13 standardizations

✅ Processing complete! All files saved to: cleanData/Context-aware_Related_CA-R_clean

🧹 Removing unknown values from Context-aware_Related_CA-R_clean...
Removing 'unknown' values from 9 files...
============================================================

Processing: Context-aware_Related_CA-R_housekeeper.csv
  - Original rows: 429
  - Found 50 'unknown' values in column 'standardized_label'
  - Rows removed: 50
  - Final rows: 379
  - Updated file saved: cleanData/Context-aware_Related_CA-R_clean/Context-aware_Related_CA-R_housekeeper.csv

Processing: Context-aware_Related_CA-R_chef.csv
  - Original rows: 402
  - Found 51 'unknown' values in column 'standardized_label'
  - Rows removed: 51
  - Final rows: 351
  - Updated file saved: cleanData/Context-aware_Related_CA-R_clean/Context-aware_Related_CA-R_chef.csv

Processing: Context-aware_Related_CA-R_farmer.csv
  - Original rows: 458
  - Found 39 'unknown' values in column 'standardized_label'
  - Rows removed: 39
  - Final rows: 419
  - Updated file saved: cleanData/Context-aware_Related_CA-R_clean/Context-aware_Related_CA-R_farmer.csv

Processing: Context-aware_Related_CA-R_dancer.csv
  - Original rows: 421
  - Found 50 'unknown' values in column 'standardized_label'
  - Rows removed: 50
  - Final rows: 371
  - Updated file saved: cleanData/Context-aware_Related_CA-R_clean/Context-aware_Related_CA-R_dancer.csv

Processing: Context-aware_Related_CA-R_bus_driver.csv
  - Original rows: 728
  - Found 23 'unknown' values in column 'standardized_label'
  - Rows removed: 23
  - Final rows: 705
  - Updated file saved: cleanData/Context-aware_Related_CA-R_clean/Context-aware_Related_CA-R_bus_driver.csv

Processing: Context-aware_Related_CA-R_janitor.csv
  - Original rows: 488
  - Found 50 'unknown' values in column 'standardized_label'
  - Rows removed: 50
  - Final rows: 438
  - Updated file saved: cleanData/Context-aware_Related_CA-R_clean/Context-aware_Related_CA-R_janitor.csv

Processing: Context-aware_Related_CA-R_athlete.csv
  - Original rows: 402
  - Found 10 'unknown' values in column 'standardized_label'
  - Rows removed: 10
  - Final rows: 392
  - Updated file saved: cleanData/Context-aware_Related_CA-R_clean/Context-aware_Related_CA-R_athlete.csv

Processing: Context-aware_Related_CA-R_ceo.csv
  - Original rows: 500
  - Found 55 'unknown' values in column 'standardized_label'
  - Rows removed: 55
  - Final rows: 445
  - Updated file saved: cleanData/Context-aware_Related_CA-R_clean/Context-aware_Related_CA-R_ceo.csv

Processing: Context-aware_Related_CA-R_police_officer.csv
  - Original rows: 694
  - Found 67 'unknown' values in column 'standardized_label'
  - Rows removed: 67
  - Final rows: 627
  - Updated file saved: cleanData/Context-aware_Related_CA-R_clean/Context-aware_Related_CA-R_police_officer.csv

============================================================
UNKNOWN VALUE REMOVAL SUMMARY
============================================================

File: Context-aware_Related_CA-R_housekeeper.csv
  📊 Rows: 429 → 379 (removed: 50)
  🗑️ standardized_label: 50 unknown values removed

File: Context-aware_Related_CA-R_chef.csv
  📊 Rows: 402 → 351 (removed: 51)
  🗑️ standardized_label: 51 unknown values removed

File: Context-aware_Related_CA-R_farmer.csv
  📊 Rows: 458 → 419 (removed: 39)
  🗑️ standardized_label: 39 unknown values removed

File: Context-aware_Related_CA-R_dancer.csv
  📊 Rows: 421 → 371 (removed: 50)
  🗑️ standardized_label: 50 unknown values removed

File: Context-aware_Related_CA-R_bus_driver.csv
  📊 Rows: 728 → 705 (removed: 23)
  🗑️ standardized_label: 23 unknown values removed

File: Context-aware_Related_CA-R_janitor.csv
  📊 Rows: 488 → 438 (removed: 50)
  🗑️ standardized_label: 50 unknown values removed

File: Context-aware_Related_CA-R_athlete.csv
  📊 Rows: 402 → 392 (removed: 10)
  🗑️ standardized_label: 10 unknown values removed

File: Context-aware_Related_CA-R_ceo.csv
  📊 Rows: 500 → 445 (removed: 55)
  🗑️ standardized_label: 55 unknown values removed

File: Context-aware_Related_CA-R_police_officer.csv
  📊 Rows: 694 → 627 (removed: 67)
  🗑️ standardized_label: 67 unknown values removed

✅ Total rows removed across all files: 395
✅ Completed processing Context-aware_Related_CA-R → Context-aware_Related_CA-R_clean

🔄 Processing folder: Context-aware_Unrelated_CA-U
📁 Output folder: Context-aware_Unrelated_CA-U_clean
Found 10 CSV files to process
============================================================

Processing: Context-aware_Unrelated_CA-U_dancer.csv
  - Loaded 346 rows, 4 columns
Processing column: dimension
  - Standardized 33 values in column 'dimension'
Processing column: label
  - Standardized 6 values in column 'label'
  - Aggregated to 333 rows
  - Saved to: cleanData/Context-aware_Unrelated_CA-U_clean/Context-aware_Unrelated_CA-U_dancer.csv

Processing: Context-aware_Unrelated_CA-U_ceo.csv
  - Loaded 380 rows, 4 columns
Processing column: dimension
  - Standardized 0 values in column 'dimension'
Processing column: label
  - Standardized 8 values in column 'label'
  - Aggregated to 371 rows
  - Saved to: cleanData/Context-aware_Unrelated_CA-U_clean/Context-aware_Unrelated_CA-U_ceo.csv

Processing: Context-aware_Unrelated_CA-U_bus_driver.csv
  - Loaded 465 rows, 4 columns
Processing column: dimension
  - Standardized 17 values in column 'dimension'
Processing column: label
  - Standardized 11 values in column 'label'
  - Aggregated to 443 rows
  - Saved to: cleanData/Context-aware_Unrelated_CA-U_clean/Context-aware_Unrelated_CA-U_bus_driver.csv

Processing: Context-aware_Unrelated_CA-U_farmer.csv
  - Loaded 329 rows, 4 columns
Processing column: dimension
  - Standardized 4 values in column 'dimension'
Processing column: label
  - Standardized 6 values in column 'label'
  - Aggregated to 324 rows
  - Saved to: cleanData/Context-aware_Unrelated_CA-U_clean/Context-aware_Unrelated_CA-U_farmer.csv

Processing: Context-aware_Unrelated_CA-U_musician.csv
  - Loaded 507 rows, 4 columns
Processing column: dimension
  - Standardized 0 values in column 'dimension'
Processing column: label
  - Standardized 13 values in column 'label'
  - Aggregated to 495 rows
  - Saved to: cleanData/Context-aware_Unrelated_CA-U_clean/Context-aware_Unrelated_CA-U_musician.csv

Processing: Context-aware_Unrelated_CA-U_janitor.csv
  - Loaded 519 rows, 4 columns
Processing column: dimension
  - Standardized 0 values in column 'dimension'
Processing column: label
  - Standardized 7 values in column 'label'
  - Aggregated to 512 rows
  - Saved to: cleanData/Context-aware_Unrelated_CA-U_clean/Context-aware_Unrelated_CA-U_janitor.csv

Processing: Context-aware_Unrelated_CA-U_chef.csv
  - Loaded 261 rows, 4 columns
Processing column: dimension
  - Standardized 9 values in column 'dimension'
Processing column: label
  - Standardized 3 values in column 'label'
  - Aggregated to 251 rows
  - Saved to: cleanData/Context-aware_Unrelated_CA-U_clean/Context-aware_Unrelated_CA-U_chef.csv

Processing: Context-aware_Unrelated_CA-U_police_officer.csv
  - Loaded 293 rows, 4 columns
Processing column: dimension
  - Standardized 0 values in column 'dimension'
Processing column: label
  - Standardized 5 values in column 'label'
  - Aggregated to 289 rows
  - Saved to: cleanData/Context-aware_Unrelated_CA-U_clean/Context-aware_Unrelated_CA-U_police_officer.csv

Processing: Context-aware_Unrelated_CA-U_housekeeper.csv
  - Loaded 449 rows, 4 columns
Processing column: dimension
  - Standardized 0 values in column 'dimension'
Processing column: label
  - Standardized 5 values in column 'label'
  - Aggregated to 438 rows
  - Saved to: cleanData/Context-aware_Unrelated_CA-U_clean/Context-aware_Unrelated_CA-U_housekeeper.csv

Processing: Context-aware_Unrelated_CA-U_athlete.csv
  - Loaded 570 rows, 4 columns
Processing column: dimension
  - Standardized 1 values in column 'dimension'
Processing column: label
  - Standardized 15 values in column 'label'
  - Aggregated to 557 rows
  - Saved to: cleanData/Context-aware_Unrelated_CA-U_clean/Context-aware_Unrelated_CA-U_athlete.csv

============================================================
PROCESSING SUMMARY
============================================================

File: Context-aware_Unrelated_CA-U_dancer.csv
  📊 Rows: 346 → 333
  🔄 dimension: 33 standardizations
  🔄 label: 6 standardizations

File: Context-aware_Unrelated_CA-U_ceo.csv
  📊 Rows: 380 → 371
  🔄 dimension: 0 standardizations
  🔄 label: 8 standardizations

File: Context-aware_Unrelated_CA-U_bus_driver.csv
  📊 Rows: 465 → 443
  🔄 dimension: 17 standardizations
  🔄 label: 11 standardizations

File: Context-aware_Unrelated_CA-U_farmer.csv
  📊 Rows: 329 → 324
  🔄 dimension: 4 standardizations
  🔄 label: 6 standardizations

File: Context-aware_Unrelated_CA-U_musician.csv
  📊 Rows: 507 → 495
  🔄 dimension: 0 standardizations
  🔄 label: 13 standardizations

File: Context-aware_Unrelated_CA-U_janitor.csv
  📊 Rows: 519 → 512
  🔄 dimension: 0 standardizations
  🔄 label: 7 standardizations

File: Context-aware_Unrelated_CA-U_chef.csv
  📊 Rows: 261 → 251
  🔄 dimension: 9 standardizations
  🔄 label: 3 standardizations

File: Context-aware_Unrelated_CA-U_police_officer.csv
  📊 Rows: 293 → 289
  🔄 dimension: 0 standardizations
  🔄 label: 5 standardizations

File: Context-aware_Unrelated_CA-U_housekeeper.csv
  📊 Rows: 449 → 438
  🔄 dimension: 0 standardizations
  🔄 label: 5 standardizations

File: Context-aware_Unrelated_CA-U_athlete.csv
  📊 Rows: 570 → 557
  🔄 dimension: 1 standardizations
  🔄 label: 15 standardizations

✅ Processing complete! All files saved to: cleanData/Context-aware_Unrelated_CA-U_clean

🧹 Removing unknown values from Context-aware_Unrelated_CA-U_clean...
Removing 'unknown' values from 10 files...
============================================================

Processing: Context-aware_Unrelated_CA-U_dancer.csv
  - Original rows: 333
  - Found 16 'unknown' values in column 'standardized_label'
  - Rows removed: 16
  - Final rows: 317
  - Updated file saved: cleanData/Context-aware_Unrelated_CA-U_clean/Context-aware_Unrelated_CA-U_dancer.csv

Processing: Context-aware_Unrelated_CA-U_ceo.csv
  - Original rows: 371
  - Found 19 'unknown' values in column 'standardized_label'
  - Rows removed: 19
  - Final rows: 352
  - Updated file saved: cleanData/Context-aware_Unrelated_CA-U_clean/Context-aware_Unrelated_CA-U_ceo.csv

Processing: Context-aware_Unrelated_CA-U_bus_driver.csv
  - Original rows: 443
  - Found 17 'unknown' values in column 'standardized_label'
  - Rows removed: 17
  - Final rows: 426
  - Updated file saved: cleanData/Context-aware_Unrelated_CA-U_clean/Context-aware_Unrelated_CA-U_bus_driver.csv

Processing: Context-aware_Unrelated_CA-U_farmer.csv
  - Original rows: 324
  - Found 17 'unknown' values in column 'standardized_label'
  - Rows removed: 17
  - Final rows: 307
  - Updated file saved: cleanData/Context-aware_Unrelated_CA-U_clean/Context-aware_Unrelated_CA-U_farmer.csv

Processing: Context-aware_Unrelated_CA-U_musician.csv
  - Original rows: 495
  - Found 12 'unknown' values in column 'standardized_label'
  - Rows removed: 12
  - Final rows: 483
  - Updated file saved: cleanData/Context-aware_Unrelated_CA-U_clean/Context-aware_Unrelated_CA-U_musician.csv

Processing: Context-aware_Unrelated_CA-U_janitor.csv
  - Original rows: 512
  - Found 18 'unknown' values in column 'standardized_label'
  - Rows removed: 18
  - Final rows: 494
  - Updated file saved: cleanData/Context-aware_Unrelated_CA-U_clean/Context-aware_Unrelated_CA-U_janitor.csv

Processing: Context-aware_Unrelated_CA-U_chef.csv
  - Original rows: 251
  - Found 7 'unknown' values in column 'standardized_label'
  - Rows removed: 7
  - Final rows: 244
  - Updated file saved: cleanData/Context-aware_Unrelated_CA-U_clean/Context-aware_Unrelated_CA-U_chef.csv

Processing: Context-aware_Unrelated_CA-U_police_officer.csv
  - Original rows: 289
  - Found 8 'unknown' values in column 'standardized_label'
  - Rows removed: 8
  - Final rows: 281
  - Updated file saved: cleanData/Context-aware_Unrelated_CA-U_clean/Context-aware_Unrelated_CA-U_police_officer.csv

Processing: Context-aware_Unrelated_CA-U_housekeeper.csv
  - Original rows: 438
  - Found 18 'unknown' values in column 'standardized_label'
  - Rows removed: 18
  - Final rows: 420
  - Updated file saved: cleanData/Context-aware_Unrelated_CA-U_clean/Context-aware_Unrelated_CA-U_housekeeper.csv

Processing: Context-aware_Unrelated_CA-U_athlete.csv
  - Original rows: 557
  - Found 16 'unknown' values in column 'standardized_label'
  - Rows removed: 16
  - Final rows: 541
  - Updated file saved: cleanData/Context-aware_Unrelated_CA-U_clean/Context-aware_Unrelated_CA-U_athlete.csv

============================================================
UNKNOWN VALUE REMOVAL SUMMARY
============================================================

File: Context-aware_Unrelated_CA-U_dancer.csv
  📊 Rows: 333 → 317 (removed: 16)
  🗑️ standardized_label: 16 unknown values removed

File: Context-aware_Unrelated_CA-U_ceo.csv
  📊 Rows: 371 → 352 (removed: 19)
  🗑️ standardized_label: 19 unknown values removed

File: Context-aware_Unrelated_CA-U_bus_driver.csv
  📊 Rows: 443 → 426 (removed: 17)
  🗑️ standardized_label: 17 unknown values removed

File: Context-aware_Unrelated_CA-U_farmer.csv
  📊 Rows: 324 → 307 (removed: 17)
  🗑️ standardized_label: 17 unknown values removed

File: Context-aware_Unrelated_CA-U_musician.csv
  📊 Rows: 495 → 483 (removed: 12)
  🗑️ standardized_label: 12 unknown values removed

File: Context-aware_Unrelated_CA-U_janitor.csv
  📊 Rows: 512 → 494 (removed: 18)
  🗑️ standardized_label: 18 unknown values removed

File: Context-aware_Unrelated_CA-U_chef.csv
  📊 Rows: 251 → 244 (removed: 7)
  🗑️ standardized_label: 7 unknown values removed

File: Context-aware_Unrelated_CA-U_police_officer.csv
  📊 Rows: 289 → 281 (removed: 8)
  🗑️ standardized_label: 8 unknown values removed

File: Context-aware_Unrelated_CA-U_housekeeper.csv
  📊 Rows: 438 → 420 (removed: 18)
  🗑️ standardized_label: 18 unknown values removed

File: Context-aware_Unrelated_CA-U_athlete.csv
  📊 Rows: 557 → 541 (removed: 16)
  🗑️ standardized_label: 16 unknown values removed

✅ Total rows removed across all files: 148
✅ Completed processing Context-aware_Unrelated_CA-U → Context-aware_Unrelated_CA-U_clean

🔄 Processing folder: role_count_aggregation
📁 Output folder: role_count_aggregation_clean
Found 10 CSV files to process
============================================================

Processing: farmer.csv
  - Loaded 803 rows, 4 columns
Processing column: dimension
  - Standardized 13 values in column 'dimension'
Processing column: label
  - Standardized 24 values in column 'label'
  - Aggregated to 777 rows
  - Saved to: cleanData/role_count_aggregation_clean/farmer.csv

Processing: ceo.csv
  - Loaded 857 rows, 4 columns
Processing column: dimension
  - Standardized 14 values in column 'dimension'

In [15]:
# Verify the complete clean data structure
print("🔍 VERIFICATION: Clean Data Structure")
print("=" * 60)

# Check the cleanData directory structure
cleandata_path = Path("cleanData")
if cleandata_path.exists():
    print(f"📁 cleanData directory created successfully!")
    
    # Show the folder structure
    clean_folders = [d for d in cleandata_path.iterdir() if d.is_dir()]
    print(f"\n📂 Created {len(clean_folders)} clean folders:")
    
    total_files = 0
    total_rows = 0
    
    for clean_folder in sorted(clean_folders):
        csv_files = list(clean_folder.glob("*.csv"))
        folder_rows = 0
        
        for csv_file in csv_files:
            df = pd.read_csv(csv_file)
            folder_rows += len(df)
        
        total_files += len(csv_files)
        total_rows += folder_rows
        
        print(f"   📁 {clean_folder.name}:")
        print(f"      📄 {len(csv_files)} CSV files")
        print(f"      📊 {folder_rows} total rows")
        
        # Show sample of first file in folder to verify structure
        if csv_files:
            sample_df = pd.read_csv(csv_files[0])
            print(f"      🔍 Sample columns: {list(sample_df.columns)}")
            
            # Check for unknown values
            unknown_count = 0
            for col in ['standardized_dimension', 'standardized_label']:
                if col in sample_df.columns:
                    unknown_in_col = (sample_df[col].astype(str).str.lower() == 'unknown').sum()
                    unknown_count += unknown_in_col
            
            if unknown_count == 0:
                print(f"      ✅ No unknown values found")
            else:
                print(f"      ⚠️  {unknown_count} unknown values still present")
    
    print(f"\n📈 OVERALL SUMMARY:")
    print(f"   📁 Total clean folders: {len(clean_folders)}")
    print(f"   📄 Total CSV files: {total_files}")
    print(f"   📊 Total rows across all files: {total_rows}")
    print(f"   🧹 All data standardized and cleaned")
    
    print(f"\n🎉 SUCCESS! All folders processed and clean data structure created!")
    
else:
    print("❌ cleanData directory was not created")

# Show the mapping of original folders to clean folders
print(f"\n📋 FOLDER MAPPING:")
original_folders = ["role_count_aggregation", "Context-aware_Related_CA-R", 
                   "Context-aware_Unrelated_CA-U", "Context-free_CF"]
for folder in original_folders:
    clean_name = f"{folder}_clean"
    print(f"   {folder} → {clean_name}")

🔍 VERIFICATION: Clean Data Structure
============================================================
📁 cleanData directory created successfully!

📂 Created 4 clean folders:
   📁 Context-aware_Related_CA-R_clean:
      📄 9 CSV files
      📊 4127 total rows
      🔍 Sample columns: ['cohort', 'standardized_dimension', 'standardized_label', 'count']
      ✅ No unknown values found
   📁 Context-aware_Unrelated_CA-U_clean:
      📄 10 CSV files
      📊 3865 total rows
      🔍 Sample columns: ['cohort', 'standardized_dimension', 'standardized_label', 'count']
      ✅ No unknown values found
   📁 Context-free_CF_clean:
      📄 10 CSV files
      📊 2542 total rows
      🔍 Sample columns: ['cohort', 'standardized_dimension', 'standardized_label', 'count']
      ✅ No unknown values found
   📁 role_count_aggregation_clean:
      📄 10 CSV files
      📊 8429 total rows
      🔍 Sample columns: ['cohort', 'standardized_dimension', 'standardized_label', 'count']
      ✅ No unknown values found

📈 OVERALL SUMMARY:
   📁 Total clean folders: 4
   📄 Total CSV files: 39
   📊 Total rows across all files: 18963
   🧹 All data standardized and cleaned

🎉 SUCCESS! All folders processed and clean data structure created!

📋 FOLDER MAPPING:
   role_count_aggregation → role_count_aggregation_clean
   Context-aware_Related_CA-R → Context-aware_Related_CA-R_clean
   Context-aware_Unrelated_CA-U → Context-aware_Unrelated_CA-U_clean
   Context-free_CF → Context-free_CF_clean

## 🔍 DataFrame Exploration & Filtering

Now that your data is cleaned, let's work with it as DataFrames for easy filtering and navigation!

In [8]:
# Function to load individual CSV files as DataFrames for exploration
def load_csv_as_dataframe(csv_path):
    """Load a specific CSV file as a DataFrame"""
    df = pd.read_csv(csv_path)
    print(f"📊 Loaded: {csv_path.name}")
    print(f"📏 Shape: {df.shape} (rows, columns)")
    print(f"🏷️ Columns: {list(df.columns)}")
    return df

def explore_dataframe(df, name="DataFrame"):
    """Explore a DataFrame with basic info and samples"""
    print(f"🔍 EXPLORING {name.upper()}")
    print("=" * 50)
    print(f"📏 Shape: {df.shape}")
    print(f"🏷️ Columns: {list(df.columns)}")
    print(f"📊 Data types:\n{df.dtypes}")
    print(f"\n📈 Basic info:")
    print(f"  • Non-null values per column:\n{df.count()}")
    print(f"\n🔍 First 5 rows:")
    return df.head()

# If you want to work with your combined data (already loaded as df_all)
print("✅ You already have your data loaded as 'df_all' DataFrame!")
print(f"📊 Current df_all shape: {df_all.shape}")
print(f"🏷️ Columns: {list(df_all.columns)}")
print(f"📁 Contexts available: {df_all['context_type'].unique()}")
print(f"👤 Roles available: {df_all['role'].nunique()} unique roles")

✅ You already have your data loaded as 'df_all' DataFrame!
📊 Current df_all shape: (18963, 7)
🏷️ Columns: ['cohort', 'standardized_dimension', 'standardized_label', 'count', 'context_type', 'role', 'filename']
📁 Contexts available: ['Original' 'Context-Free' 'Context-Aware Related'
 'Context-Aware Unrelated']
👤 Roles available: 10 unique roles

In [9]:
# 🔍 DATAFRAME FILTERING & NAVIGATION EXAMPLES

print("🚀 DATAFRAME FILTERING & NAVIGATION EXAMPLES")
print("=" * 60)

# 1. Basic DataFrame exploration
print("\n1️⃣ BASIC DATAFRAME INFO:")
print(f"   📊 Total rows: {len(df_all):,}")
print(f"   📋 Columns: {list(df_all.columns)}")
print(f"   🔍 Data types:\n{df_all.dtypes}")

# 2. Show first few rows
print("\n2️⃣ FIRST 5 ROWS:")
display(df_all.head())

# 3. Filtering examples
print("\n3️⃣ FILTERING EXAMPLES:")

# Filter by context type
print("🔹 Filter by Context Type (Context-Free):")
context_free_data = df_all[df_all['context_type'] == 'Context-Free']
print(f"   Rows: {len(context_free_data):,}")
display(context_free_data.head(3))

# Filter by role
print("\n🔹 Filter by Role (e.g., 'ceo'):")
ceo_data = df_all[df_all['role'] == 'ceo']
print(f"   Rows: {len(ceo_data):,}")
if len(ceo_data) > 0:
    display(ceo_data.head(3))
else:
    print("   No 'ceo' role found. Available roles:", df_all['role'].unique()[:10])

🚀 DATAFRAME FILTERING & NAVIGATION EXAMPLES
============================================================

1️⃣ BASIC DATAFRAME INFO:
   📊 Total rows: 18,963
   📋 Columns: ['cohort', 'standardized_dimension', 'standardized_label', 'count', 'context_type', 'role', 'filename']
   🔍 Data types:
cohort                    object
standardized_dimension    object
standardized_label        object
count                      int64
context_type              object
role                      object
filename                  object
dtype: object

2️⃣ FIRST 5 ROWS:

,cohort,standardized_dimension,standardized_label,count,context_type,role,filename
0,atmosphere,aesthetic_qualities,cinematic,38,Original,farmer,farmer
1,atmosphere,aesthetic_qualities,dreamy,3,Original,farmer,farmer
2,atmosphere,aesthetic_qualities,quality cinematic,6,Original,farmer,farmer
3,atmosphere,aesthetic_qualities,quality dreamy,3,Original,farmer,farmer
4,atmosphere,aesthetic_qualities,quality realistic,8,Original,farmer,farmer

3️⃣ FILTERING EXAMPLES:
🔹 Filter by Context Type (Context-Free):
   Rows: 2,542

,cohort,standardized_dimension,standardized_label,count,context_type,role,filename
8429,atmosphere,aesthetic_qualities,cinematic,1,Context-Free,ceo,Context-free_CF_ceo
8430,atmosphere,aesthetic_qualities,minimal,1,Context-Free,ceo,Context-free_CF_ceo
8431,atmosphere,aesthetic_qualities,realistic,8,Context-Free,ceo,Context-free_CF_ceo

🔹 Filter by Role (e.g., 'ceo'):
   Rows: 1,737

,cohort,standardized_dimension,standardized_label,count,context_type,role,filename
727,atmosphere,aesthetic_qualities,cinematic,14,Original,ceo,ceo
728,atmosphere,aesthetic_qualities,minimal,4,Original,ceo,ceo
729,atmosphere,aesthetic_qualities,realistic,32,Original,ceo,ceo

In [10]:
# 4️⃣ ADVANCED FILTERING TECHNIQUES

print("4️⃣ ADVANCED FILTERING TECHNIQUES:")
print("-" * 40)

# Multiple conditions
print("🔹 Multiple Conditions (Context-Free AND high count):")
high_count_cf = df_all[(df_all['context_type'] == 'Context-Free') & (df_all['count'] > 100)]
print(f"   Rows matching both conditions: {len(high_count_cf):,}")
if len(high_count_cf) > 0:
    display(high_count_cf.head(3))

# Filter by dimension
print("\n🔹 Filter by Dimension:")
dimensions = df_all['standardized_dimension'].value_counts().head(5)
print(f"   Top 5 dimensions: {list(dimensions.index)}")
top_dimension = dimensions.index[0]
dim_data = df_all[df_all['standardized_dimension'] == top_dimension]
print(f"   Rows with '{top_dimension}' dimension: {len(dim_data):,}")
display(dim_data.head(3))

# Filter by label
print("\n🔹 Filter by Label:")
labels = df_all['standardized_label'].value_counts().head(5)
print(f"   Top 5 labels: {list(labels.index)}")
top_label = labels.index[0] 
label_data = df_all[df_all['standardized_label'] == top_label]
print(f"   Rows with '{top_label}' label: {len(label_data):,}")
display(label_data.head(3))

4️⃣ ADVANCED FILTERING TECHNIQUES:
----------------------------------------
🔹 Multiple Conditions (Context-Free AND high count):
   Rows matching both conditions: 0

🔹 Filter by Dimension:
   Top 5 dimensions: ['type', 'note', 'material', 'color', 'artifacts']
   Rows with 'type' dimension: 2,595

,cohort,standardized_dimension,standardized_label,count,context_type,role,filename
320,objects,type,accessory,2,Original,farmer,farmer
321,objects,type,agricultural,1,Original,farmer,farmer
322,objects,type,agricultural product,3,Original,farmer,farmer

🔹 Filter by Label:
   Top 5 labels: ['black', 'medium', 'brown', 'white', 'gray']
   Rows with 'black' label: 265

,cohort,standardized_dimension,standardized_label,count,context_type,role,filename
244,objects,color,black,4,Original,farmer,farmer
279,objects,object_colors,black,2,Original,farmer,farmer
448,people,clothing_color,black,13,Original,farmer,farmer

In [11]:
# 5️⃣ DATAFRAME NAVIGATION & SORTING

print("5️⃣ DATAFRAME NAVIGATION & SORTING:")
print("-" * 40)

# Sorting
print("🔹 Sort by Count (highest first):")
sorted_by_count = df_all.sort_values('count', ascending=False)
display(sorted_by_count.head(3))

print("\n🔹 Sort by Multiple Columns (Context, then Count):")
multi_sort = df_all.sort_values(['context_type', 'count'], ascending=[True, False])
display(multi_sort.head(3))

# Grouping and aggregation
print("\n🔹 Group by Context Type (summary statistics):")
context_summary = df_all.groupby('context_type').agg({
    'count': ['sum', 'mean', 'max', 'min'],
    'role': 'nunique',
    'standardized_dimension': 'nunique',
    'standardized_label': 'nunique'
}).round(2)
display(context_summary)

# Column navigation
print("\n🔹 Column Information:")
print(f"   📋 All columns: {list(df_all.columns)}")
print(f"   🔢 Numeric columns: {list(df_all.select_dtypes(include=['number']).columns)}")
print(f"   📝 Text columns: {list(df_all.select_dtypes(include=['object']).columns)}")

# Sample specific columns
print("\n🔹 Select Specific Columns:")
key_columns = ['context_type', 'role', 'standardized_dimension', 'standardized_label', 'count']
df_subset = df_all[key_columns]
print(f"   Selected columns: {key_columns}")
display(df_subset.head(3))

5️⃣ DATAFRAME NAVIGATION & SORTING:
----------------------------------------
🔹 Sort by Count (highest first):

,cohort,standardized_dimension,standardized_label,count,context_type,role,filename
4941,objects,side,center,176,Original,athlete,athlete
4936,objects,plane,foreground,169,Original,athlete,athlete
759,background,object_counts_by_position,midground center,138,Original,ceo,ceo

🔹 Sort by Multiple Columns (Context, then Count):

,cohort,standardized_dimension,standardized_label,count,context_type,role,filename
11204,objects,texture,smooth,100,Context-Aware Related,housekeeper,Context-aware_Related_CA-R_housekeeper
11122,objects,condition,good,80,Context-Aware Related,housekeeper,Context-aware_Related_CA-R_housekeeper
11174,objects,size_class,medium,70,Context-Aware Related,housekeeper,Context-aware_Related_CA-R_housekeeper

🔹 Group by Context Type (summary statistics):

                         count                   role standardized_dimension  \
                           sum  mean  max min nunique                nunique
context_type
Context-Aware Related    19562  4.74  100   0       9                    143
Context-Aware Unrelated  20283  5.25  129   0      10                    138
Context-Free              9692  3.81   59   0      10                    100
Original                 49551  5.88  176   0      10                    184

                        standardized_label
                                   nunique
context_type
Context-Aware Related                 2076
Context-Aware Unrelated               1886
Context-Free                          1389
Original                              4293

🔹 Column Information:
   📋 All columns: ['cohort', 'standardized_dimension', 'standardized_label', 'count', 'context_type', 'role', 'filename']
   🔢 Numeric columns: ['count']
   📝 Text columns: ['cohort', 'standardized_dimension', 'standardized_label', 'context_type', 'role', 'filename']

🔹 Select Specific Columns:
   Selected columns: ['context_type', 'role', 'standardized_dimension', 'standardized_label', 'count']

  context_type    role standardized_dimension standardized_label  count
0     Original  farmer    aesthetic_qualities          cinematic     38
1     Original  farmer    aesthetic_qualities             dreamy      3
2     Original  farmer    aesthetic_qualities  quality cinematic      6

In [12]:
# 6️⃣ INTERACTIVE DATAFRAME UTILITIES

print("6️⃣ INTERACTIVE DATAFRAME UTILITIES:")
print("-" * 40)

def explore_column_values(df, column_name):
    """Explore unique values in a column"""
    if column_name not in df.columns:
        print(f"❌ Column '{column_name}' not found!")
        print(f"Available columns: {list(df.columns)}")
        return
    
    print(f"🔍 EXPLORING COLUMN: {column_name}")
    print(f"   📊 Unique values: {df[column_name].nunique()}")
    print(f"   📋 Value counts (top 10):")
    value_counts = df[column_name].value_counts().head(10)
    for value, count in value_counts.items():
        print(f"      • {value}: {count:,}")
    
    if df[column_name].dtype in ['int64', 'float64']:
        print(f"   📈 Statistics:")
        print(f"      • Mean: {df[column_name].mean():.2f}")
        print(f"      • Median: {df[column_name].median():.2f}")
        print(f"      • Min: {df[column_name].min()}")
        print(f"      • Max: {df[column_name].max()}")

def filter_and_explore(df, filters):
    """Apply multiple filters and explore the result"""
    filtered_df = df.copy()
    
    print("🔍 APPLYING FILTERS:")
    for column, value in filters.items():
        if isinstance(value, list):
            filtered_df = filtered_df[filtered_df[column].isin(value)]
            print(f"   • {column} in {value}")
        else:
            filtered_df = filtered_df[filtered_df[column] == value]
            print(f"   • {column} == '{value}'")
    
    print(f"\n📊 RESULT: {len(filtered_df):,} rows")
    if len(filtered_df) > 0:
        return filtered_df.head(10)  # Return top 10 rows
    else:
        print("❌ No rows match the filters!")
        return None

# Example usage
print("\n🔹 Explore 'context_type' column:")
explore_column_values(df_all, 'context_type')

print("\n🔹 Explore 'count' column:")
explore_column_values(df_all, 'count')

print("\n🔹 Filter Example - Context-Free data for a specific role:")
# Get a role that exists
sample_role = df_all['role'].value_counts().index[0]
result = filter_and_explore(df_all, {
    'context_type': 'Context-Free',
    'role': sample_role
})
if result is not None:
    display(result)

6️⃣ INTERACTIVE DATAFRAME UTILITIES:
----------------------------------------

🔹 Explore 'context_type' column:
🔍 EXPLORING COLUMN: context_type
   📊 Unique values: 4
   📋 Value counts (top 10):
      • Original: 8,429
      • Context-Aware Related: 4,127
      • Context-Aware Unrelated: 3,865
      • Context-Free: 2,542

🔹 Explore 'count' column:
🔍 EXPLORING COLUMN: count
   📊 Unique values: 110
   📋 Value counts (top 10):
      • 1: 9,310
      • 2: 2,263
      • 3: 1,114
      • 4: 923
      • 6: 567
      • 5: 563
      • 10: 455
      • 8: 434
      • 7: 380
      • 9: 376
   📈 Statistics:
      • Mean: 5.23
      • Median: 1.00
      • Min: 0
      • Max: 176

🔹 Filter Example - Context-Free data for a specific role:
🔍 APPLYING FILTERS:
   • context_type == 'Context-Free'
   • role == 'bus_driver'

📊 RESULT: 358 rows

,cohort,standardized_dimension,standardized_label,count,context_type,role,filename
10613,atmosphere,aesthetic_qualities,cinematic,1,Context-Free,bus_driver,Context-free_CF_bus_driver
10614,atmosphere,aesthetic_qualities,realistic,6,Context-Free,bus_driver,Context-free_CF_bus_driver
10615,atmosphere,color_temperature,cool,2,Context-Free,bus_driver,Context-free_CF_bus_driver
10616,atmosphere,color_temperature,neutral,3,Context-Free,bus_driver,Context-free_CF_bus_driver
10617,atmosphere,color_temperature,warm,1,Context-Free,bus_driver,Context-free_CF_bus_driver
10618,atmosphere,contrast_level,medium,6,Context-Free,bus_driver,Context-free_CF_bus_driver
10619,atmosphere,dominant_palette,black,4,Context-Free,bus_driver,Context-free_CF_bus_driver
10620,atmosphere,dominant_palette,brown,5,Context-Free,bus_driver,Context-free_CF_bus_driver
10621,atmosphere,dominant_palette,cyan,1,Context-Free,bus_driver,Context-free_CF_bus_driver
10622,atmosphere,mood,calm,10,Context-Free,bus_driver,Context-free_CF_bus_driver

In [13]:
# 7️⃣ LOAD INDIVIDUAL CSV FILES AS DATAFRAMES

print("7️⃣ LOAD INDIVIDUAL CSV FILES AS DATAFRAMES:")
print("-" * 50)

def load_individual_csvs():
    """Load individual CSV files from cleanData directory"""
    cleandata_path = Path("cleanData")
    csv_files = {}
    
    for clean_folder in cleandata_path.iterdir():
        if clean_folder.is_dir():
            folder_csvs = {}
            for csv_file in clean_folder.glob("*.csv"):
                df = pd.read_csv(csv_file)
                filename = csv_file.stem
                folder_csvs[filename] = df
                print(f"✅ Loaded: {csv_file.relative_to(cleandata_path)} ({df.shape[0]} rows, {df.shape[1]} cols)")
            
            csv_files[clean_folder.name] = folder_csvs
    
    return csv_files

def search_dataframe(df, search_term, columns=None):
    """Search for a term across DataFrame columns"""
    if columns is None:
        columns = df.select_dtypes(include=['object']).columns
    
    mask = pd.Series([False] * len(df))
    for col in columns:
        if col in df.columns:
            mask |= df[col].astype(str).str.contains(search_term, case=False, na=False)
    
    result = df[mask]
    print(f"🔍 Found {len(result)} rows containing '{search_term}'")
    return result

# Load all individual CSVs
print("🔄 Loading all individual CSV files...")
csv_dataframes = load_individual_csvs()

print(f"\n📁 Loaded data structure:")
for folder_name, folder_data in csv_dataframes.items():
    print(f"   📂 {folder_name}: {len(folder_data)} CSV files")
    for filename in list(folder_data.keys())[:3]:  # Show first 3 files
        print(f"      • {filename}")
    if len(folder_data) > 3:
        print(f"      • ... and {len(folder_data) - 3} more files")

print("\n💡 TIP: Access individual DataFrames like this:")
print("   csv_dataframes['folder_name']['filename']")
print("   Example: csv_dataframes['Context-free_CF_clean']['Context-free_CF_game_developer']")

7️⃣ LOAD INDIVIDUAL CSV FILES AS DATAFRAMES:
--------------------------------------------------
🔄 Loading all individual CSV files...
✅ Loaded: role_count_aggregation_clean/farmer.csv (727 rows, 4 cols)
✅ Loaded: role_count_aggregation_clean/ceo.csv (749 rows, 4 cols)
✅ Loaded: role_count_aggregation_clean/dancer.csv (728 rows, 4 cols)
✅ Loaded: role_count_aggregation_clean/housekeeper.csv (864 rows, 4 cols)
✅ Loaded: role_count_aggregation_clean/police_officer.csv (900 rows, 4 cols)
✅ Loaded: role_count_aggregation_clean/chef.csv (681 rows, 4 cols)
✅ Loaded: role_count_aggregation_clean/athlete.csv (922 rows, 4 cols)
✅ Loaded: role_count_aggregation_clean/bus_driver.csv (1230 rows, 4 cols)
✅ Loaded: role_count_aggregation_clean/janitor.csv (932 rows, 4 cols)
✅ Loaded: role_count_aggregation_clean/musician.csv (696 rows, 4 cols)
✅ Loaded: Context-free_CF_clean/Context-free_CF_ceo.csv (191 rows, 4 cols)
✅ Loaded: Context-free_CF_clean/Context-free_CF_housekeeper.csv (287 rows, 4 cols)
✅ Loaded: Context-free_CF_clean/Context-free_CF_farmer.csv (211 rows, 4 cols)
✅ Loaded: Context-free_CF_clean/Context-free_CF_janitor.csv (269 rows, 4 cols)
✅ Loaded: Context-free_CF_clean/Context-free_CF_dancer.csv (221 rows, 4 cols)
✅ Loaded: Context-free_CF_clean/Context-free_CF_police_officer.csv (227 rows, 4 cols)
✅ Loaded: Context-free_CF_clean/Context-free_CF_musician.csv (308 rows, 4 cols)
✅ Loaded: Context-free_CF_clean/Context-free_CF_athlete.csv (202 rows, 4 cols)
✅ Loaded: Context-free_CF_clean/Context-free_CF_chef.csv (268 rows, 4 cols)
✅ Loaded: Context-free_CF_clean/Context-free_CF_bus_driver.csv (358 rows, 4 cols)
✅ Loaded: Context-aware_Related_CA-R_clean/Context-aware_Related_CA-R_housekeeper.csv (379 rows, 4 cols)
✅ Loaded: Context-aware_Related_CA-R_clean/Context-aware_Related_CA-R_chef.csv (351 rows, 4 cols)
✅ Loaded: Context-aware_Related_CA-R_clean/Context-aware_Related_CA-R_farmer.csv (419 rows, 4 cols)
✅ Loaded: Context-aware_Related_CA-R_clean/Context-aware_Related_CA-R_dancer.csv (371 rows, 4 cols)
✅ Loaded: Context-aware_Related_CA-R_clean/Context-aware_Related_CA-R_bus_driver.csv (705 rows, 4 cols)
✅ Loaded: Context-aware_Related_CA-R_clean/Context-aware_Related_CA-R_janitor.csv (438 rows, 4 cols)
✅ Loaded: Context-aware_Related_CA-R_clean/Context-aware_Related_CA-R_athlete.csv (392 rows, 4 cols)
✅ Loaded: Context-aware_Related_CA-R_clean/Context-aware_Related_CA-R_ceo.csv (445 rows, 4 cols)
✅ Loaded: Context-aware_Related_CA-R_clean/Context-aware_Related_CA-R_police_officer.csv (627 rows, 4 cols)
✅ Loaded: Context-aware_Unrelated_CA-U_clean/Context-aware_Unrelated_CA-U_dancer.csv (317 rows, 4 cols)
✅ Loaded: Context-aware_Unrelated_CA-U_clean/Context-aware_Unrelated_CA-U_ceo.csv (352 rows, 4 cols)
✅ Loaded: Context-aware_Unrelated_CA-U_clean/Context-aware_Unrelated_CA-U_bus_driver.csv (426 rows, 4 cols)
✅ Loaded: Context-aware_Unrelated_CA-U_clean/Context-aware_Unrelated_CA-U_farmer.csv (307 rows, 4 cols)
✅ Loaded: Context-aware_Unrelated_CA-U_clean/Context-aware_Unrelated_CA-U_musician.csv (483 rows, 4 cols)
✅ Loaded: Context-aware_Unrelated_CA-U_clean/Context-aware_Unrelated_CA-U_janitor.csv (494 rows, 4 cols)
✅ Loaded: Context-aware_Unrelated_CA-U_clean/Context-aware_Unrelated_CA-U_chef.csv (244 rows, 4 cols)
✅ Loaded: Context-aware_Unrelated_CA-U_clean/Context-aware_Unrelated_CA-U_police_officer.csv (281 rows, 4 cols)
✅ Loaded: Context-aware_Unrelated_CA-U_clean/Context-aware_Unrelated_CA-U_housekeeper.csv (420 rows, 4 cols)
✅ Loaded: Context-aware_Unrelated_CA-U_clean/Context-aware_Unrelated_CA-U_athlete.csv (541 rows, 4 cols)

📁 Loaded data structure:
   📂 role_count_aggregation_clean: 10 CSV files
      • farmer
      • ceo
      • dancer
      • ... and 7 more files
   📂 Context-free_CF_clean: 10 CSV files
      • Context-free_CF_ceo
      • Context-free_CF_housekeeper
      • Context-free_CF_farmer
      • ... and 7 more files
   📂 Context-aware_Related_CA-R_clean: 9 CSV files
      • Context-aware_Related_CA-R_housekeeper
      • Context-aware_Related_CA-R_chef
      • Context-aware_Related_CA-R_farmer
      • ... and 6 more files
   📂 Context-aware_Unrelated_CA-U_clean: 10 CSV files
      • Context-aware_Unrelated_CA-U_dancer
      • Context-aware_Unrelated_CA-U_ceo
      • Context-aware_Unrelated_CA-U_bus_driver
      • ... and 7 more files

💡 TIP: Access individual DataFrames like this:
   csv_dataframes['folder_name']['filename']
   Example: csv_dataframes['Context-free_CF_clean']['Context-free_CF_game_developer']

In [14]:
# 📚 DATAFRAME CHEAT SHEET & QUICK REFERENCE

print("📚 DATAFRAME CHEAT SHEET & QUICK REFERENCE")
print("=" * 60)

print("""
🔍 BASIC EXPLORATION:
   df.head()              # First 5 rows
   df.tail()              # Last 5 rows  
   df.info()              # Column info & data types
   df.describe()          # Statistical summary
   df.shape               # (rows, columns)
   df.columns             # Column names
   df.dtypes              # Data types

🔎 FILTERING:
   df[df['column'] == 'value']                    # Simple filter
   df[df['column'].isin(['val1', 'val2'])]       # Multiple values
   df[(df['col1'] == 'val1') & (df['col2'] > 10)] # Multiple conditions
   df[df['column'].str.contains('text')]          # Text search
   df[df['column'].notna()]                       # Non-null values

📊 SORTING & GROUPING:
   df.sort_values('column')                       # Sort by column
   df.sort_values(['col1', 'col2'])              # Sort by multiple
   df.groupby('column').sum()                     # Group and aggregate
   df.value_counts()                              # Count unique values

🎯 COLUMN OPERATIONS:
   df['new_col'] = df['col1'] + df['col2']       # Create new column
   df[['col1', 'col2']]                          # Select columns
   df.drop('column', axis=1)                     # Remove column
   df.rename(columns={'old': 'new'})             # Rename column

🔢 STATISTICS:
   df['column'].mean()                           # Average
   df['column'].sum()                            # Sum
   df['column'].nunique()                        # Unique count
   df['column'].value_counts()                   # Count each value
""")

print("\n🚀 EXAMPLES WITH YOUR DATA:")
print("-" * 30)
print(f"# Filter by role:")
print(f"ceo_data = df_all[df_all['role'] == 'ceo']")
print(f"")
print(f"# Get top 10 highest counts:")
print(f"top_counts = df_all.nlargest(10, 'count')")  
print(f"")
print(f"# Group by context and sum counts:")
print(f"context_totals = df_all.groupby('context_type')['count'].sum()")
print(f"")
print(f"# Search for specific dimension:")
print(f"gender_data = df_all[df_all['standardized_dimension'].str.contains('gender', case=False)]")
print(f"")
print(f"# Multiple filters:")
print(f"filtered = df_all[(df_all['context_type'] == 'Context-Free') & (df_all['count'] > 50)]")

print(f"\n✅ Your data is ready to explore! Try running the examples above.")

📚 DATAFRAME CHEAT SHEET & QUICK REFERENCE
============================================================

🔍 BASIC EXPLORATION:
   df.head()              # First 5 rows
   df.tail()              # Last 5 rows
   df.info()              # Column info & data types
   df.describe()          # Statistical summary
   df.shape               # (rows, columns)
   df.columns             # Column names
   df.dtypes              # Data types

🔎 FILTERING:
   df[df['column'] == 'value']                    # Simple filter
   df[df['column'].isin(['val1', 'val2'])]       # Multiple values
   df[(df['col1'] == 'val1') & (df['col2'] > 10)] # Multiple conditions
   df[df['column'].str.contains('text')]          # Text search
   df[df['column'].notna()]                       # Non-null values

📊 SORTING & GROUPING:
   df.sort_values('column')                       # Sort by column
   df.sort_values(['col1', 'col2'])              # Sort by multiple
   df.groupby('column').sum()                     # Group and aggregate
   df.value_counts()                              # Count unique values

🎯 COLUMN OPERATIONS:
   df['new_col'] = df['col1'] + df['col2']       # Create new column
   df[['col1', 'col2']]                          # Select columns
   df.drop('column', axis=1)                     # Remove column
   df.rename(columns={'old': 'new'})             # Rename column

🔢 STATISTICS:
   df['column'].mean()                           # Average
   df['column'].sum()                            # Sum
   df['column'].nunique()                        # Unique count
   df['column'].value_counts()                   # Count each value


🚀 EXAMPLES WITH YOUR DATA:
------------------------------
# Filter by role:
ceo_data = df_all[df_all['role'] == 'ceo']

# Get top 10 highest counts:
top_counts = df_all.nlargest(10, 'count')

# Group by context and sum counts:
context_totals = df_all.groupby('context_type')['count'].sum()

# Search for specific dimension:
gender_data = df_all[df_all['standardized_dimension'].str.contains('gender', case=False)]

# Multiple filters:
filtered = df_all[(df_all['context_type'] == 'Context-Free') & (df_all['count'] > 50)]

✅ Your data is ready to explore! Try running the examples above.

In [15]:
# 🎯 LIVE DEMONSTRATION - Navigate Your Clean Data

print("🎯 LIVE DEMONSTRATION - Navigate Your Clean Data")
print("=" * 60)

# Show what data you have available
print("📊 YOUR CLEAN DATA OVERVIEW:")
print(f"   • Total rows: {len(df_all):,}")
print(f"   • Contexts: {list(df_all['context_type'].unique())}")
print(f"   • Roles: {list(df_all['role'].unique())}")
print(f"   • Total data points: {df_all['count'].sum():,}")

print("\n🔍 NAVIGATION EXAMPLES:")

# 1. Browse by role
print("\n1️⃣ Browse CEO data:")
ceo_data = df_all[df_all['role'] == 'ceo']
print(f"   CEO has {len(ceo_data)} entries across {ceo_data['context_type'].nunique()} contexts")
print("   Top CEO dimensions:")
ceo_top_dims = ceo_data.groupby('standardized_dimension')['count'].sum().sort_values(ascending=False).head(5)
for dim, count in ceo_top_dims.items():
    print(f"      • {dim}: {count:,} occurrences")

# 2. Browse by context
print("\n2️⃣ Browse Context-Free data:")
cf_data = df_all[df_all['context_type'] == 'Context-Free']
print(f"   Context-Free has {len(cf_data)} entries across {cf_data['role'].nunique()} roles")
print("   Top Context-Free labels:")
cf_top_labels = cf_data.groupby('standardized_label')['count'].sum().sort_values(ascending=False).head(5)
for label, count in cf_top_labels.items():
    print(f"      • {label}: {count:,} occurrences")

# 3. Search functionality
print("\n3️⃣ Search for 'gender' related data:")
gender_data = df_all[df_all['standardized_dimension'].str.contains('gender', case=False, na=False)]
if len(gender_data) > 0:
    print(f"   Found {len(gender_data)} gender-related entries")
    print("   Gender dimensions found:")
    gender_dims = gender_data['standardized_dimension'].unique()
    for dim in gender_dims[:5]:  # Show first 5
        print(f"      • {dim}")
else:
    print("   No gender-related dimensions found")

# 4. High-impact data (highest counts)
print("\n4️⃣ Highest impact entries (top counts):")
top_entries = df_all.nlargest(5, 'count')
for idx, row in top_entries.iterrows():
    print(f"   • {row['role']} → {row['standardized_dimension']} → {row['standardized_label']}: {row['count']} occurrences")

print(f"\n💡 TIP: All your individual CSV files are also loaded!")
print(f"   Use: csv_dataframes['folder_name']['filename'] to access specific files")
print(f"   Example: csv_dataframes['Context-free_CF_clean']['Context-free_CF_ceo']")

🎯 LIVE DEMONSTRATION - Navigate Your Clean Data
============================================================
📊 YOUR CLEAN DATA OVERVIEW:
   • Total rows: 18,963
   • Contexts: ['Original', 'Context-Free', 'Context-Aware Related', 'Context-Aware Unrelated']
   • Roles: ['farmer', 'ceo', 'dancer', 'housekeeper', 'police_officer', 'chef', 'athlete', 'bus_driver', 'janitor', 'musician']
   • Total data points: 99,088

🔍 NAVIGATION EXAMPLES:

1️⃣ Browse CEO data:
   CEO has 1737 entries across 4 contexts
   Top CEO dimensions:
      • type: 768 occurrences
      • object_counts_by_position: 689 occurrences
      • color: 638 occurrences
      • plane: 460 occurrences
      • material: 448 occurrences

2️⃣ Browse Context-Free data:
   Context-Free has 2542 entries across 10 roles
   Top Context-Free labels:
      • medium: 327 occurrences
      • foreground: 249 occurrences
      • yes: 226 occurrences
      • brown: 215 occurrences
      • center: 215 occurrences

3️⃣ Search for 'gender' related data:
   Found 53 gender-related entries
   Gender dimensions found:
      • gender_presentation

4️⃣ Highest impact entries (top counts):
   • athlete → side → center: 176 occurrences
   • athlete → plane → foreground: 169 occurrences
   • ceo → object_counts_by_position → midground center: 138 occurrences
   • athlete → plane → background: 136 occurrences
   • housekeeper → texture → smooth: 130 occurrences

💡 TIP: All your individual CSV files are also loaded!
   Use: csv_dataframes['folder_name']['filename'] to access specific files
   Example: csv_dataframes['Context-free_CF_clean']['Context-free_CF_ceo']

## 📊 Add Bins Column to All Clean Files

Adding a "bins" column that counts unique labels per dimension for each row.

In [16]:
def add_bins_column_to_all_files():
    """
    Add a 'bins' column to all clean CSV files.
    Bins = number of unique labels for each dimension within that file.
    Updates files in place.
    """
    cleandata_path = Path("cleanData")
    total_files_updated = 0
    
    print("🔄 Adding 'bins' column to all clean CSV files...")
    print("=" * 60)
    
    for clean_folder in cleandata_path.iterdir():
        if clean_folder.is_dir():
            print(f"\n📂 Processing folder: {clean_folder.name}")
            folder_files_updated = 0
            
            for csv_file in clean_folder.glob("*.csv"):
                # Read the CSV file
                df = pd.read_csv(csv_file)
                
                # Check if bins column already exists
                if 'bins' in df.columns:
                    print(f"   ⚠️  {csv_file.name}: 'bins' column already exists, skipping...")
                    continue
                
                # Calculate bins for each row
                # Group by dimension and count unique labels
                dimension_label_counts = df.groupby('standardized_dimension')['standardized_label'].nunique().to_dict()
                
                # Add bins column by mapping each dimension to its label count
                df['bins'] = df['standardized_dimension'].map(dimension_label_counts)
                
                # Save the updated file (overwrite the original)
                df.to_csv(csv_file, index=False)
                
                print(f"   ✅ {csv_file.name}: Added bins column ({len(df)} rows updated)")
                folder_files_updated += 1
                total_files_updated += 1
            
            print(f"   📊 Folder summary: {folder_files_updated} files updated")
    
    print(f"\n🎉 COMPLETE! Updated {total_files_updated} CSV files with 'bins' column")
    print("   Each row now shows how many unique labels exist for that dimension within the file.")
    
    return total_files_updated

# Execute the function to update all files
files_updated = add_bins_column_to_all_files()

🔄 Adding 'bins' column to all clean CSV files...
============================================================

📂 Processing folder: role_count_aggregation_clean
   ✅ farmer.csv: Added bins column (727 rows updated)
   ✅ ceo.csv: Added bins column (749 rows updated)
   ✅ dancer.csv: Added bins column (728 rows updated)
   ✅ housekeeper.csv: Added bins column (864 rows updated)
   ✅ police_officer.csv: Added bins column (900 rows updated)
   ✅ chef.csv: Added bins column (681 rows updated)
   ✅ athlete.csv: Added bins column (922 rows updated)
   ✅ bus_driver.csv: Added bins column (1230 rows updated)
   ✅ janitor.csv: Added bins column (932 rows updated)
   ✅ musician.csv: Added bins column (696 rows updated)
   📊 Folder summary: 10 files updated

📂 Processing folder: Context-free_CF_clean
   ✅ Context-free_CF_ceo.csv: Added bins column (191 rows updated)
   ✅ Context-free_CF_housekeeper.csv: Added bins column (287 rows updated)
   ✅ Context-free_CF_farmer.csv: Added bins column (211 rows updated)
   ✅ Context-free_CF_janitor.csv: Added bins column (269 rows updated)
   ✅ Context-free_CF_dancer.csv: Added bins column (221 rows updated)
   ✅ Context-free_CF_police_officer.csv: Added bins column (227 rows updated)
   ✅ Context-free_CF_musician.csv: Added bins column (308 rows updated)
   ✅ Context-free_CF_athlete.csv: Added bins column (202 rows updated)
   ✅ Context-free_CF_chef.csv: Added bins column (268 rows updated)
   ✅ Context-free_CF_bus_driver.csv: Added bins column (358 rows updated)
   📊 Folder summary: 10 files updated

📂 Processing folder: Context-aware_Related_CA-R_clean
   ✅ Context-aware_Related_CA-R_housekeeper.csv: Added bins column (379 rows updated)
   ✅ Context-aware_Related_CA-R_chef.csv: Added bins column (351 rows updated)
   ✅ Context-aware_Related_CA-R_farmer.csv: Added bins column (419 rows updated)
   ✅ Context-aware_Related_CA-R_dancer.csv: Added bins column (371 rows updated)
   ✅ Context-aware_Related_CA-R_bus_driver.csv: Added bins column (705 rows updated)
   ✅ Context-aware_Related_CA-R_janitor.csv: Added bins column (438 rows updated)
   ✅ Context-aware_Related_CA-R_athlete.csv: Added bins column (392 rows updated)
   ✅ Context-aware_Related_CA-R_ceo.csv: Added bins column (445 rows updated)
   ✅ Context-aware_Related_CA-R_police_officer.csv: Added bins column (627 rows updated)
   📊 Folder summary: 9 files updated

📂 Processing folder: Context-aware_Unrelated_CA-U_clean
   ✅ Context-aware_Unrelated_CA-U_dancer.csv: Added bins column (317 rows updated)
   ✅ Context-aware_Unrelated_CA-U_ceo.csv: Added bins column (352 rows updated)
   ✅ Context-aware_Unrelated_CA-U_bus_driver.csv: Added bins column (426 rows updated)
   ✅ Context-aware_Unrelated_CA-U_farmer.csv: Added bins column (307 rows updated)
   ✅ Context-aware_Unrelated_CA-U_musician.csv: Added bins column (483 rows updated)
   ✅ Context-aware_Unrelated_CA-U_janitor.csv: Added bins column (494 rows updated)
   ✅ Context-aware_Unrelated_CA-U_chef.csv: Added bins column (244 rows updated)
   ✅ Context-aware_Unrelated_CA-U_police_officer.csv: Added bins column (281 rows updated)
   ✅ Context-aware_Unrelated_CA-U_housekeeper.csv: Added bins column (420 rows updated)
   ✅ Context-aware_Unrelated_CA-U_athlete.csv: Added bins column (541 rows updated)
   📊 Folder summary: 10 files updated

🎉 COMPLETE! Updated 39 CSV files with 'bins' column
   Each row now shows how many unique labels exist for that dimension within the file.

In [17]:
# 🔍 VERIFY BINS COLUMN ADDITION

print("🔍 VERIFYING BINS COLUMN ADDITION")
print("=" * 50)

# Sample a few files to verify the bins column
cleandata_path = Path("cleanData")
sample_files = []

for clean_folder in cleandata_path.iterdir():
    if clean_folder.is_dir():
        csv_files = list(clean_folder.glob("*.csv"))
        if csv_files:
            sample_files.append(csv_files[0])  # Take first file from each folder

print(f"📋 Checking {len(sample_files)} sample files:")

for i, sample_file in enumerate(sample_files[:4]):  # Check first 4 samples
    df_sample = pd.read_csv(sample_file)
    
    print(f"\n{i+1}️⃣ File: {sample_file.name}")
    print(f"   📊 Shape: {df_sample.shape}")
    print(f"   📋 Columns: {list(df_sample.columns)}")
    
    if 'bins' in df_sample.columns:
        print(f"   ✅ 'bins' column present!")
        print(f"   📈 Bins range: {df_sample['bins'].min()} to {df_sample['bins'].max()}")
        
        # Show example of bins for different dimensions
        bins_by_dim = df_sample.groupby('standardized_dimension')['bins'].first().head(5)
        print(f"   🔍 Sample dimensions and their bins:")
        for dim, bins in bins_by_dim.items():
            print(f"      • '{dim}': {bins} unique labels")
    else:
        print(f"   ❌ 'bins' column missing!")

# Show a few sample rows with the new bins column
print(f"\n📋 SAMPLE ROWS WITH BINS COLUMN:")
if sample_files:
    df_demo = pd.read_csv(sample_files[0])
    display(df_demo[['standardized_dimension', 'standardized_label', 'count', 'bins']].head())

print(f"\n💡 EXPLANATION:")
print(f"   The 'bins' column shows how many unique labels exist for each dimension")
print(f"   within the same CSV file. For example:")
print(f"   • If dimension 'color' has labels ['red', 'blue', 'green'] → bins = 3")
print(f"   • If dimension 'size' has labels ['small', 'large'] → bins = 2")

🔍 VERIFYING BINS COLUMN ADDITION
==================================================
📋 Checking 4 sample files:

1️⃣ File: farmer.csv
   📊 Shape: (727, 5)
   📋 Columns: ['cohort', 'standardized_dimension', 'standardized_label', 'count', 'bins']
   ✅ 'bins' column present!
   📈 Bins range: 1 to 108
   🔍 Sample dimensions and their bins:
      • 'activities': 17 unique labels
      • 'aesthetic_qualities': 6 unique labels
      • 'age_range': 2 unique labels
      • 'artifacts': 10 unique labels
      • 'ceiling_color': 1 unique labels

2️⃣ File: Context-free_CF_ceo.csv
   📊 Shape: (191, 5)
   📋 Columns: ['cohort', 'standardized_dimension', 'standardized_label', 'count', 'bins']
   ✅ 'bins' column present!
   📈 Bins range: 1 to 44
   🔍 Sample dimensions and their bins:
      • 'aesthetic_qualities': 3 unique labels
      • 'age_range': 1 unique labels
      • 'artifacts': 6 unique labels
      • 'clothing_colors': 5 unique labels
      • 'clothing_garment': 12 unique labels

3️⃣ File: Context-aware_Related_CA-R_housekeeper.csv
   📊 Shape: (379, 5)
   📋 Columns: ['cohort', 'standardized_dimension', 'standardized_label', 'count', 'bins']
   ✅ 'bins' column present!
   📈 Bins range: 1 to 29
   🔍 Sample dimensions and their bins:
      • 'activities': 12 unique labels
      • 'aesthetic_qualities': 3 unique labels
      • 'age_range': 2 unique labels
      • 'artifacts': 17 unique labels
      • 'clothing_color': 11 unique labels

4️⃣ File: Context-aware_Unrelated_CA-U_dancer.csv
   📊 Shape: (317, 5)
   📋 Columns: ['cohort', 'standardized_dimension', 'standardized_label', 'count', 'bins']
   ✅ 'bins' column present!
   📈 Bins range: 1 to 67
   🔍 Sample dimensions and their bins:
      • 'aesthetic_qualities': 3 unique labels
      • 'age_range': 2 unique labels
      • 'artifacts': 5 unique labels
      • 'ceiling_color': 3 unique labels
      • 'color': 16 unique labels

📋 SAMPLE ROWS WITH BINS COLUMN:

  standardized_dimension standardized_label  count  bins
0    aesthetic_qualities          cinematic     38     6
1    aesthetic_qualities             dreamy      3     6
2    aesthetic_qualities  quality cinematic      6     6
3    aesthetic_qualities     quality dreamy      3     6
4    aesthetic_qualities  quality realistic      8     6

💡 EXPLANATION:
   The 'bins' column shows how many unique labels exist for each dimension
   within the same CSV file. For example:
   • If dimension 'color' has labels ['red', 'blue', 'green'] → bins = 3
   • If dimension 'size' has labels ['small', 'large'] → bins = 2

In [18]:
# 🔄 RELOAD COMBINED DATAFRAME WITH BINS COLUMN

print("🔄 Reloading combined dataframe with updated bins column...")

# Reload the combined dataframe to include the new bins column
df_all_with_bins = load_all_clean_data()

print(f"✅ Updated combined dataframe loaded!")
print(f"📊 Shape: {df_all_with_bins.shape}")
print(f"📋 Columns: {list(df_all_with_bins.columns)}")

# Show sample data with bins
print(f"\n📋 SAMPLE DATA WITH BINS COLUMN:")
display(df_all_with_bins[['context_type', 'role', 'standardized_dimension', 'standardized_label', 'count', 'bins']].head())

# Show bins statistics
print(f"\n📈 BINS COLUMN STATISTICS:")
print(f"   • Min bins: {df_all_with_bins['bins'].min()}")
print(f"   • Max bins: {df_all_with_bins['bins'].max()}")
print(f"   • Average bins: {df_all_with_bins['bins'].mean():.1f}")
print(f"   • Median bins: {df_all_with_bins['bins'].median():.1f}")

# Show dimensions with highest and lowest bins
print(f"\n📊 DIMENSIONS WITH HIGHEST BINS (most diverse):")
high_bins = df_all_with_bins.groupby('standardized_dimension')['bins'].max().sort_values(ascending=False).head(5)
for dim, bins in high_bins.items():
    print(f"   • {dim}: {bins} unique labels")

print(f"\n📊 DIMENSIONS WITH LOWEST BINS (least diverse):")
low_bins = df_all_with_bins.groupby('standardized_dimension')['bins'].max().sort_values().head(5)
for dim, bins in low_bins.items():
    print(f"   • {dim}: {bins} unique labels")

# Update the global variable for consistency
df_all = df_all_with_bins
print(f"\n✅ Global df_all updated with bins column!")

🔄 Reloading combined dataframe with updated bins column...
✅ Updated combined dataframe loaded!
📊 Shape: (18963, 8)
📋 Columns: ['cohort', 'standardized_dimension', 'standardized_label', 'count', 'bins', 'context_type', 'role', 'filename']

📋 SAMPLE DATA WITH BINS COLUMN:

  context_type    role standardized_dimension standardized_label  count  bins
0     Original  farmer    aesthetic_qualities          cinematic     38     6
1     Original  farmer    aesthetic_qualities             dreamy      3     6
2     Original  farmer    aesthetic_qualities  quality cinematic      6     6
3     Original  farmer    aesthetic_qualities     quality dreamy      3     6
4     Original  farmer    aesthetic_qualities  quality realistic      8     6

📈 BINS COLUMN STATISTICS:
   • Min bins: 1
   • Max bins: 259
   • Average bins: 28.0
   • Median bins: 14.0

📊 DIMENSIONS WITH HIGHEST BINS (most diverse):
   • type: 259 unique labels
   • texture: 74 unique labels
   • uncertainty: 67 unique labels
   • note: 67 unique labels
   • type_distribution: 67 unique labels

📊 DIMENSIONS WITH LOWEST BINS (least diverse):
   • object_counts_foreground_right: 1 unique labels
   • surfaces_ceiling_texture: 1 unique labels
   • surfaces_ceiling_finish: 1 unique labels
   • source_type: 1 unique labels
   • source_summary: 1 unique labels

✅ Global df_all updated with bins column!

In [19]:
# 📊 BINS COLUMN ADDITION SUMMARY

print("📊 BINS COLUMN ADDITION - SUMMARY REPORT")
print("=" * 60)

print("✅ COMPLETED SUCCESSFULLY!")
print(f"   • Added 'bins' column to all CSV files in cleanData/ directory")
print(f"   • Updated {len(list(Path('cleanData').rglob('*.csv')))} CSV files")
print(f"   • All files updated in-place (no new files created)")

print(f"\n🔍 BINS COLUMN EXPLANATION:")
print(f"   The 'bins' column shows the number of unique labels that exist")
print(f"   for each dimension within the same CSV file.")
print(f"   ")
print(f"   Example: If a dimension 'color' appears in a file with labels:")
print(f"   ['red', 'blue', 'green', 'red', 'blue'] → bins = 3 (unique labels)")

print(f"\n📈 BINS STATISTICS ACROSS ALL DATA:")
print(f"   • Range: {df_all['bins'].min()} to {df_all['bins'].max()} unique labels per dimension")
print(f"   • Average: {df_all['bins'].mean():.1f} unique labels per dimension")
print(f"   • Most diverse dimension: 'type' with {df_all[df_all['standardized_dimension']=='type']['bins'].max()} unique labels")

print(f"\n🎯 USAGE IDEAS:")
print(f"   • Filter high-diversity dimensions: df[df['bins'] > 50]")
print(f"   • Find low-diversity dimensions: df[df['bins'] == 1]")
print(f"   • Compare diversity across contexts: df.groupby('context_type')['bins'].mean()")
print(f"   • Analyze dimension complexity by role: df.groupby('role')['bins'].describe()")

print(f"\n✅ Your clean CSV files now have the 'bins' column!")
print(f"   All data is ready for analysis with dimension diversity information.")

📊 BINS COLUMN ADDITION - SUMMARY REPORT
============================================================
✅ COMPLETED SUCCESSFULLY!
   • Added 'bins' column to all CSV files in cleanData/ directory
   • Updated 39 CSV files
   • All files updated in-place (no new files created)

🔍 BINS COLUMN EXPLANATION:
   The 'bins' column shows the number of unique labels that exist
   for each dimension within the same CSV file.

   Example: If a dimension 'color' appears in a file with labels:
   ['red', 'blue', 'green', 'red', 'blue'] → bins = 3 (unique labels)

📈 BINS STATISTICS ACROSS ALL DATA:
   • Range: 1 to 259 unique labels per dimension
   • Average: 28.0 unique labels per dimension
   • Most diverse dimension: 'type' with 259 unique labels

🎯 USAGE IDEAS:
   • Filter high-diversity dimensions: df[df['bins'] > 50]
   • Find low-diversity dimensions: df[df['bins'] == 1]
   • Compare diversity across contexts: df.groupby('context_type')['bins'].mean()
   • Analyze dimension complexity by role: df.groupby('role')['bins'].describe()

✅ Your clean CSV files now have the 'bins' column!
   All data is ready for analysis with dimension diversity information.

## ✅ Data Preprocessing Complete!

🎉 **All data has been successfully cleaned and processed!**

### What was accomplished:
- ✅ Standardized dimension and label names across all files
- ✅ Removed unknown values ("unknown", "not_applicable", etc.)
- ✅ Processed 4 context types: Original, Context-Free, Context-Aware Related, Context-Aware Unrelated
- ✅ Cleaned data saved to `cleanData/` directory with organized folder structure

### Next Steps:
📊 **For comprehensive data visualization and analysis**, open the companion notebook:
**`data_visualization.ipynb`**

This notebook contains:
- 📈 Overview charts of data distribution across contexts and roles
- 🔍 Detailed analysis of cohorts, dimensions, and labels  
- 👥 Role-specific insights and comparisons
- 🎯 Actionable insights for bias detection
- 🔧 Utility functions for custom analysis

The preprocessing pipeline is now complete and ready for bias detection analysis!